<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <PropertyGroup>
    <TargetFramework>$(BenchmarkTargetFramework)</TargetFramework>
    <TargetFrameworks>$(BenchmarkTargetFramework)</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
