interface Node {
  id: ID!
}

type PageInfo @shareable {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  node("ID of the object." id: ID!): Node @lookup @shareable
  nodes("The list of node IDs." ids: [ID!]!): [Node]! @shareable
  userById(id: ID!): User @lookup
  userByUsername(username: String!): User @lookup
  users(first: Int after: String last: Int before: String): UsersConnection
}

type User implements Node {
  id: ID!
  name: String! @shareable
  birthdate: String!
  username: String!
}

type UsersConnection {
  pageInfo: PageInfo!
  edges: [UsersEdge!]
  nodes: [User!]
}

type UsersEdge {
  cursor: String!
  node: User!
}