query {
  products {
    nodes {
      reviews {
        nodes {
          stars
          author {
            birthdate
            username
          }
          b: product {
            weight
          }
          stars
          product {
            weight
            deliveryEstimate(zip: "Foo")
            pictureFileName
            price
            quantity
            item {
              product {
                weight
                deliveryEstimate(zip: "Foo")
                pictureFileName
                reviews {
                  edges {
                    node {
                      author {
                        birthdate
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      b:reviews {
        nodes {
          stars
          author {
            birthdate
            username
          }
          b: product {
            weight
          }
          stars
          product {
            weight
            deliveryEstimate(zip: "Foo")
            pictureFileName
            price
            quantity
            item {
              product {
                weight
                deliveryEstimate(zip: "Foo")
                pictureFileName
                reviews {
                  edges {
                    node {
                      author {
                        birthdate
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      weight
    }
  }
}