//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawberryShake.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StrawberryShake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Response_BodyAndExceptionAreNull {
            get {
                return ResourceManager.GetString("Response_BodyAndExceptionAreNull", resourceCulture);
            }
        }
        
        internal static string HttpOperationExecutor_ExecuteAsync_NoResult {
            get {
                return ResourceManager.GetString("HttpOperationExecutor_ExecuteAsync_NoResult", resourceCulture);
            }
        }
        
        internal static string ClassBuilder_SetName_ClassNameCannotBeNull {
            get {
                return ResourceManager.GetString("ClassBuilder_SetName_ClassNameCannotBeNull", resourceCulture);
            }
        }
        
        internal static string ClassBuilder_AddImplements_TypeNameCannotBeNull {
            get {
                return ResourceManager.GetString("ClassBuilder_AddImplements_TypeNameCannotBeNull", resourceCulture);
            }
        }
        
        internal static string AssignmentBuilder_Build_Incomplete {
            get {
                return ResourceManager.GetString("AssignmentBuilder_Build_Incomplete", resourceCulture);
            }
        }
        
        internal static string CodeFileBuilder_NamespaceCannotBeNull {
            get {
                return ResourceManager.GetString("CodeFileBuilder_NamespaceCannotBeNull", resourceCulture);
            }
        }
    }
}
