<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HotChocolate.Adapters.OpenApi</RootNamespace>
    <PackageId>HotChocolate.Adapters.OpenApi.AspNetCore</PackageId>
    <TargetFrameworks>$(OpenApiTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HotChocolate.Adapters.OpenApi" />
    <InternalsVisibleTo Include="HotChocolate.Fusion.Adapters.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <!-- Dependency of Microsoft.AspNetCore.OpenApi. Pinned to secure version. -->
    <PackageReference Include="Microsoft.OpenApi" VersionOverride="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\src\Types.Abstractions\HotChocolate.Types.Abstractions.csproj" />
    <ProjectReference Include="..\Adapters.OpenApi.Core\HotChocolate.Adapters.OpenApi.Core.csproj" />
  </ItemGroup>

</Project>
