<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.6" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <RootNamespace>FusionReleasePipeline.AppHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="../../../../src/HotChocolate/Fusion/src/Fusion.Aspire/HotChocolate.Fusion.Aspire.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference Include="../Gateway/Gateway.csproj" />
    <ProjectReference Include="../Products/Products.csproj" />
    <ProjectReference Include="../Reviews/Reviews.csproj" />
  </ItemGroup>
</Project>
