🌶️ hot chocolate:
  - "### Product\n\nHot Chocolate"

🌶️ strawberry shake:
  - "### Product\n\nStrawberry Shake"

🌶️ banana cake pop:
  - "### Product\n\nBanana Cake Pop"

🌶️ green donut:
  - "### Product\n\nGreen Donut"
