🌶️ hot chocolate:
  - "### Product\n\nHot Chocolate"

🌶️ strawberry shake:
  - "### Product\n\nStrawberry Shake"

🌶️ nitro:
  - "### Product\n\nNitro"

🌶️ green donut:
  - "### Product\n\nGreen Donut"
