name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
commitish: main
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
categories:
  - title: '📚 Documentation'
    labels:
      - '📚 documentation'
  - title: '🌶️ Banana Cake Pop'
    labels:
      - '🌶️ banana cake pop'
  - title: '🌶️ Green Donut'
    labels:
      - '🌶️ green donut'
  - title: '🌶️ Hot Chocolate'
    labels:
      - '🌶️ hot chocolate'
  - title: '🌶️ Marshmallow Pie'
    labels:
      - '🌶️ marshmallow pie'
  - title: '🌶️ Strawberry Shake'
    labels:
      - '🌶️ strawberry shake'
  - title: '🌶️ Website'
    labels:
      - '🌶️ website'
  - title: '🧰 Maintenance'
    labels:
      - '🧰 maintenance'
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS