# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - '📌 pinned'
  - 'security'
  - '🎉 enhancement'
  - '🎨 refactoring'
  - '🗣 discussion'
  - '📚 documentation'
  - 'repro-validated'
# Label to use when marking an issue as stale
staleLabel: 'needs-repro'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Make sure your bug report contains a clear repro of your issue.
  Read more on how to provide repro [here]().
  Bug reports that do not provide a repro will be automatically closed after 7 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
