language: csharp
mono: latest
dotnet: 2.1.401
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9
branches:
  only:
  - build
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - chmod +x build/dotnet-install.sh
  - chmod +x ./build.sh
  - export DOTNET_RUNTIME_INSTALL_DIR="$PWD/.dotnetcli"
  - build/dotnet-install.sh --shared-runtime --version 1.0.9 --install-dir "$DOTNET_RUNTIME_INSTALL_DIR"
script:
  - ./build.sh -t Tests
