//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Language.Properties {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangUtf8Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangUtf8Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Language.Properties.LangUtf8Resources", typeof(LangUtf8Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string GraphQLData_Empty {
            get {
                return ResourceManager.GetString("GraphQLData_Empty", resourceCulture);
            }
        }

        internal static string ParseMany_InvalidOpenToken {
            get {
                return ResourceManager.GetString("ParseMany_InvalidOpenToken", resourceCulture);
            }
        }

        internal static string Parser_InvalidScalarToken {
            get {
                return ResourceManager.GetString("Parser_InvalidScalarToken", resourceCulture);
            }
        }

        internal static string Parser_InvalidToken {
            get {
                return ResourceManager.GetString("Parser_InvalidToken", resourceCulture);
            }
        }

        internal static string ThrowHelper_Reader_InvalidToken {
            get {
                return ResourceManager.GetString("ThrowHelper_Reader_InvalidToken", resourceCulture);
            }
        }

        internal static string Reader_UnexpectedDigitAfterDot {
            get {
                return ResourceManager.GetString("Reader_UnexpectedDigitAfterDot", resourceCulture);
            }
        }

        internal static string Reader_UnexpectedPunctuatorToken {
            get {
                return ResourceManager.GetString("Reader_UnexpectedPunctuatorToken", resourceCulture);
            }
        }

        internal static string SourceText_Empty {
            get {
                return ResourceManager.GetString("SourceText_Empty", resourceCulture);
            }
        }

        internal static string Utf8Helper_InvalidEscapeChar {
            get {
                return ResourceManager.GetString("Utf8Helper_InvalidEscapeChar", resourceCulture);
            }
        }

        internal static string Utf8Helper_InvalidQuoteEscapeCount {
            get {
                return ResourceManager.GetString("Utf8Helper_InvalidQuoteEscapeCount", resourceCulture);
            }
        }

        internal static string NewLineMustBeGreaterOrEqualToOne {
            get {
                return ResourceManager.GetString("NewLineMustBeGreaterOrEqualToOne", resourceCulture);
            }
        }

        internal static string UnexpectedDigit {
            get {
                return ResourceManager.GetString("UnexpectedDigit", resourceCulture);
            }
        }

        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }

        internal static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }

        internal static string InvalidCharacterEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidCharacterEscapeSequence", resourceCulture);
            }
        }

        internal static string InvalidCharacterWithinString {
            get {
                return ResourceManager.GetString("InvalidCharacterWithinString", resourceCulture);
            }
        }

        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }

        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }

        internal static string Utf8GraphQLReader_ReadPunctuatorToken_InvalidState {
            get {
                return ResourceManager.GetString("Utf8GraphQLReader_ReadPunctuatorToken_InvalidState", resourceCulture);
            }
        }

        internal static string ThrowHelper_UnexpectedProperty {
            get {
                return ResourceManager.GetString("ThrowHelper_UnexpectedProperty", resourceCulture);
            }
        }

        internal static string ThrowHelper_InvalidRequestStructure {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidRequestStructure", resourceCulture);
            }
        }

        internal static string ThrowHelper_NoIdAndNoQuery {
            get {
                return ResourceManager.GetString("ThrowHelper_NoIdAndNoQuery", resourceCulture);
            }
        }

        internal static string ThrowHelper_QueryMustBeStringOrNull {
            get {
                return ResourceManager.GetString("ThrowHelper_QueryMustBeStringOrNull", resourceCulture);
            }
        }

        internal static string ThrowHelper_ExpectedObjectOrNull {
            get {
                return ResourceManager.GetString("ThrowHelper_ExpectedObjectOrNull", resourceCulture);
            }
        }

        internal static string ThrowHelper_ExpectedStringOrNull {
            get {
                return ResourceManager.GetString("ThrowHelper_ExpectedStringOrNull", resourceCulture);
            }
        }

        internal static string ThrowHelper_UnexpectedToken {
            get {
                return ResourceManager.GetString("ThrowHelper_UnexpectedToken", resourceCulture);
            }
        }

        internal static string Utf8GraphQLReader_Read_MaxAllowedTokensReached {
            get {
                return ResourceManager.GetString("Utf8GraphQLReader_Read_MaxAllowedTokensReached", resourceCulture);
            }
        }

        internal static string Utf8GraphQLParser_Start_MaxAllowedNodesReached {
            get {
                return ResourceManager.GetString("Utf8GraphQLParser_Start_MaxAllowedNodesReached", resourceCulture);
            }
        }

        internal static string Utf8GraphQLParser_Start_MaxAllowedFieldsReached {
            get {
                return ResourceManager.GetString("Utf8GraphQLParser_Start_MaxAllowedFieldsReached", resourceCulture);
            }
        }
    }
}
