//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Language.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangWebResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangWebResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Language.Properties.LangWebResources", typeof(LangWebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SourceText_Empty {
            get {
                return ResourceManager.GetString("SourceText_Empty", resourceCulture);
            }
        }
        
        internal static string ComputeHash_FormatNotSupported {
            get {
                return ResourceManager.GetString("ComputeHash_FormatNotSupported", resourceCulture);
            }
        }
        
        internal static string ParseMany_InvalidOpenToken {
            get {
                return ResourceManager.GetString("ParseMany_InvalidOpenToken", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidVariablesValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidVariablesValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidExtensionsValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidExtensionsValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_UnknownRequestProperty {
            get {
                return ResourceManager.GetString("ThrowHelper_UnknownRequestProperty", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidQueryValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidQueryValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidDocumentIdValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidDocumentIdValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidOperationNameValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidOperationNameValue", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidOnErrorValue {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidOnErrorValue", resourceCulture);
            }
        }
        
        internal static string Utf8GraphQLRequestParser_Parse_EmptyJSONDocument {
            get {
                return ResourceManager.GetString("Utf8GraphQLRequestParser_Parse_EmptyJSONDocument", resourceCulture);
            }
        }
        
        internal static string Utf8GraphQLRequestParser_Parse_InvalidJSONDocument_ {
            get {
                return ResourceManager.GetString("Utf8GraphQLRequestParser_Parse_InvalidJSONDocument_", resourceCulture);
            }
        }
        
        internal static string Utf8GraphQLRequestParser_Parse_InvalidRequestStructure {
            get {
                return ResourceManager.GetString("Utf8GraphQLRequestParser_Parse_InvalidRequestStructure", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_InvalidOperationTypeStructure {
            get {
                return ResourceManager.GetString("ThrowHelper_InvalidOperationTypeStructure", resourceCulture);
            }
        }
    }
}
