<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TargetFramework>$(LatestTargetFramework)</TargetFramework>
    <TargetFrameworks>$(LatestTargetFramework)</TargetFrameworks>
  </PropertyGroup>
</Project>
