<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Test.props', '$(MSBuildThisFileDirectory)'))" />

  <PropertyGroup>
    <AssemblyName>ChilliCream.Nitro.Fusion.Tests</AssemblyName>
    <RootNamespace>ChilliCream.Nitro.Fusion</RootNamespace>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ChilliCream.Nitro.Fusion\ChilliCream.Nitro.Fusion.csproj" />
  </ItemGroup>

</Project>
