//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Fusion.Language.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FusionLanguageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FusionLanguageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Fusion.Language.Properties.FusionLanguageResources", typeof(FusionLanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CodeIsNotPunctuator {
            get {
                return ResourceManager.GetString("CodeIsNotPunctuator", resourceCulture);
            }
        }
        
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        internal static string MaxAllowedNodesExceeded {
            get {
                return ResourceManager.GetString("MaxAllowedNodesExceeded", resourceCulture);
            }
        }
        
        internal static string MaxAllowedTokensExceeded {
            get {
                return ResourceManager.GetString("MaxAllowedTokensExceeded", resourceCulture);
            }
        }
        
        internal static string NewLineMustBeGreaterThanOrEqualToOne {
            get {
                return ResourceManager.GetString("NewLineMustBeGreaterThanOrEqualToOne", resourceCulture);
            }
        }
        
        internal static string SourceTextCannotBeEmpty {
            get {
                return ResourceManager.GetString("SourceTextCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }
        
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
    }
}
