<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <LangVersion>Preview</LangVersion>
    <AssemblyName>HotChocolate.CostAnalysis.Core.Benchmarks</AssemblyName>
    <RootNamespace>HotChocolate.CostAnalysis</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>HC8002;$(NoWarn)</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CostAnalysis.Core\HotChocolate.CostAnalysis.Core.csproj" />
    <ProjectReference Include="..\..\..\Mutable\src\Types.Mutable\HotChocolate.Types.Mutable.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="__resources__\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
