namespace Mocha.Transport.RabbitMQ;

/// <summary>
/// Represents a topology shape conflict that occurs when merging two topology entities
/// (exchange or queue) with different declared values for the same property.
/// This exception is thrown during topology configuration when the declared entity shape
/// conflicts with the convention-generated entity shape, indicating an ambiguous or
/// contradictory configuration that cannot be reconciled silently.
/// </summary>
public sealed class RabbitMQTopologyShapeConflictException(
    string entityType,
    string entityName,
    string propertyName,
    object? declaredValue,
    object? conventionValue)
    : Exception(FormatMessage(entityType, entityName, propertyName, declaredValue, conventionValue))
{
    /// <summary>
    /// Gets the entity type that experienced the shape conflict (e.g., "exchange" or "queue").
    /// </summary>
    public string EntityType => entityType;

    /// <summary>
    /// Gets the name of the entity (exchange or queue) that experienced the shape conflict.
    /// </summary>
    public string EntityName => entityName;

    /// <summary>
    /// Gets the name of the property where the conflict occurred.
    /// </summary>
    public string PropertyName => propertyName;

    /// <summary>
    /// Gets the value declared explicitly by the user through configuration.
    /// </summary>
    public object? DeclaredValue => declaredValue;

    /// <summary>
    /// Gets the value generated by the framework convention.
    /// </summary>
    public object? ConventionValue => conventionValue;

    private static string FormatMessage(
        string entityType,
        string entityName,
        string propertyName,
        object? declaredValue,
        object? conventionValue)
    {
        return $"Shape conflict on {entityType} '{entityName}': property '{propertyName}' "
            + $"has declared value {FormatValue(declaredValue)} "
            + $"but convention generated {FormatValue(conventionValue)}. "
            + "Declared shape must match the expected topology.";
    }

    private static string FormatValue(object? value)
    {
        return value switch
        {
            null => "null",
            string s => $"'{s}'",
            bool b => b.ToString().ToLowerInvariant(),
            _ => value.ToString() ?? "null"
        };
    }
}
