namespace Mocha.Transport.RabbitMQ;

/// <summary>
/// Defines the provenance values reported for RabbitMQ topology entities and links, indicating
/// whether a resource was declared explicitly by the user or generated by the framework.
/// </summary>
public static class RabbitMQTopologyProvenance
{
    /// <summary>
    /// Identifies a resource that was declared explicitly through a user descriptor call such as
    /// DeclareExchange, DeclareQueue, or DeclareBinding.
    /// </summary>
    public const string Declared = "declared";

    /// <summary>
    /// Identifies a resource that was generated by the framework, for example by a convention,
    /// endpoint infrastructure, or reply plumbing.
    /// </summary>
    public const string Convention = "convention";

    /// <summary>
    /// Identifies a resource owned by a receive endpoint, typically a queue or satellite (error/skip queue)
    /// provisioned during endpoint lifecycle. Resources with this provenance can be merged with declared
    /// entities by identity, where declared properties win and other properties are filled in from the
    /// endpoint-owned entity.
    /// </summary>
    public const string Endpoint = "endpoint";
}
