using System.Collections.Immutable;
using RabbitMQ.Client;

namespace Mocha.Transport.RabbitMQ;

/// <summary>
/// Represents a RabbitMQ exchange entity with its configuration.
/// </summary>
public sealed class RabbitMQExchange : TopologyResource<RabbitMQExchangeConfiguration>, IRabbitMQResource
{
    private ImmutableArray<RabbitMQBinding> _bindings = [];

    /// <summary>
    /// Gets the name of this exchange as declared in RabbitMQ.
    /// </summary>
    public string Name { get; private set; } = null!;

    /// <summary>
    /// Gets the cached string representation of the exchange name, optimized for repeated use in publish operations.
    /// </summary>
    public CachedString CachedName { get; private set; } = null!;

    /// <summary>
    /// Gets a value indicating whether this exchange is automatically provisioned during topology setup.
    /// When <c>null</c>, the transport-level default is used.
    /// </summary>
    public bool? AutoProvision { get; private set; }

    /// <summary>
    /// Gets the exchange type (e.g., "direct", "fanout", "topic", "headers").
    /// </summary>
    public string Type { get; private set; } = null!;

    /// <summary>
    /// Gets a value indicating whether this exchange survives broker restarts.
    /// </summary>
    public bool Durable { get; private set; }

    /// <summary>
    /// Gets a value indicating whether this exchange is automatically deleted when no longer in use.
    /// </summary>
    public bool AutoDelete { get; private set; }

    /// <summary>
    /// Gets the additional exchange arguments for advanced configuration (e.g., alternate-exchange).
    /// </summary>
    public ImmutableDictionary<string, object?> Arguments { get; private set; } = ImmutableDictionary<string, object?>.Empty;

    /// <summary>
    /// Gets the bindings attached to this exchange (both outgoing and incoming).
    /// </summary>
    public ImmutableArray<RabbitMQBinding> Bindings => _bindings;

    /// <summary>
    /// Gets the provenance of this resource, indicating whether it was declared explicitly by the
    /// user or generated by the framework.
    /// </summary>
    public string Provenance { get; private set; } = RabbitMQTopologyProvenance.Convention;

    protected override void OnInitialize(RabbitMQExchangeConfiguration configuration)
    {
        Name = configuration.Name;
        CachedName = new CachedString(Name);
        Durable = configuration.Durable ?? true;
        Type = configuration.Type ?? "fanout";
        AutoDelete = configuration.AutoDelete ?? false;
        Arguments = configuration.Arguments?.ToImmutableDictionary(kv => kv.Key, kv => (object?)kv.Value) ?? ImmutableDictionary<string, object?>.Empty;
        AutoProvision = configuration.AutoProvision;
        Provenance = configuration.Provenance;
    }

    protected override void OnComplete(RabbitMQExchangeConfiguration configuration)
    {
        var address = new UriBuilder(Topology.Address);
        address.Path = Path.Combine(address.Path, "e", configuration.Name);
        Address = address.Uri;
    }

    internal void AddBinding(RabbitMQBinding binding)
    {
        ImmutableInterlocked.Update(ref _bindings, (current) => current.Add(binding));
    }

    /// <summary>
    /// Merges an incoming configuration into this entity, applying the 3.5 merge rules:
    /// declared non-null scalar wins; convention fills the rest; Arguments union per key;
    /// AutoProvision strengthens (true wins); provenance upgrades convention to endpoint to declared.
    /// A shape conflict (both sides declared, different scalar value) throws
    /// <see cref="RabbitMQTopologyShapeConflictException"/>.
    /// </summary>
    /// <param name="configuration">The incoming configuration to merge from.</param>
    /// <exception cref="RabbitMQTopologyShapeConflictException">
    /// Thrown when both this entity and the incoming configuration carry explicitly declared
    /// values for the same scalar property and those values differ.
    /// </exception>
    internal void MergeFrom(RabbitMQExchangeConfiguration configuration)
    {
        var incomingProvenance = configuration.Provenance;
        var existingIsDeclared = Provenance == RabbitMQTopologyProvenance.Declared;
        var incomingIsDeclared = incomingProvenance == RabbitMQTopologyProvenance.Declared;

        // Scalar shape: declared non-null incoming wins; both declared + different = conflict.
        if (configuration.Type is not null)
        {
            if (existingIsDeclared && incomingIsDeclared && Type != configuration.Type)
            {
                throw new RabbitMQTopologyShapeConflictException("exchange", Name, "Type", Type, configuration.Type);
            }

            Type = configuration.Type;
        }

        if (configuration.Durable is not null)
        {
            if (existingIsDeclared && incomingIsDeclared && Durable != configuration.Durable.Value)
            {
                throw new RabbitMQTopologyShapeConflictException("exchange", Name, "Durable", Durable, configuration.Durable.Value);
            }

            Durable = configuration.Durable.Value;
        }

        if (configuration.AutoDelete is not null)
        {
            if (existingIsDeclared && incomingIsDeclared && AutoDelete != configuration.AutoDelete.Value)
            {
                throw new RabbitMQTopologyShapeConflictException("exchange", Name, "AutoDelete", AutoDelete, configuration.AutoDelete.Value);
            }

            AutoDelete = configuration.AutoDelete.Value;
        }

        // Arguments: union per key; incoming key wins on collision.
        if (configuration.Arguments is not null)
        {
            var builder = Arguments.ToBuilder();

            foreach (var (key, value) in configuration.Arguments)
            {
                builder[key] = value;
            }

            Arguments = builder.ToImmutable();
        }

        // AutoProvision: strengthen (true wins over null or false).
        if (AutoProvision is null)
        {
            AutoProvision = configuration.AutoProvision;
        }
        else if (configuration.AutoProvision == true)
        {
            AutoProvision = true;
        }

        // Provenance: upgrade only, never downgrade.
        Provenance = UpgradeProvenance(Provenance, incomingProvenance);
    }

    private static string UpgradeProvenance(string existing, string incoming)
    {
        if (existing == RabbitMQTopologyProvenance.Declared)
        {
            return existing;
        }

        if (existing == RabbitMQTopologyProvenance.Endpoint
            && incoming == RabbitMQTopologyProvenance.Convention)
        {
            return existing;
        }

        return incoming;
    }

    /// <summary>
    /// Declares this exchange on the broker using the specified channel.
    /// </summary>
    /// <param name="channel">The RabbitMQ channel to use for declaring the exchange.</param>
    /// <param name="cancellationToken">A token to cancel the provisioning operation.</param>
    public async Task ProvisionAsync(IChannel channel, CancellationToken cancellationToken)
    {
        await channel.ExchangeDeclareAsync(
            CachedName.Value,
            Type,
            Durable,
            AutoDelete,
            Arguments,
            cancellationToken: cancellationToken);
    }
}
