name: Bug Report
description: Report a bug to help us improve.
labels: [🐛 bug]
body:
  - type: markdown
    attributes:
      value: |
        **Before you start...**

        This form is only for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [documentation](https://chillicream.com/docs)
        - Ask on [Slack](https://slack.chillicream.com/)
        - Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/hotchocolate)

        Also try to search for your issue &ndash; it may have already been answered or even fixed in the main branch.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below, instead of commenting on the old issue.
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which of our products is affected by this bug?
      options:
        - Hot Chocolate
        - Strawberry Shake
        - Banana Cake Pop
        - Green Donut
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the selected product are you running?
      placeholder: "12.0.0"
    validations:
      required: true
  - type: input
    id: reproduction-url
    attributes:
      label: Link to minimal reproduction
      description: |
        Add the URL to a public Git repository or ZIP file.

        The reproduction should be **minimal** - i.e. it should contain only the bare minimum amount of code needed
        to show the bug.

        Please do not just fill in a random link. The issue will be closed if no valid reproduction is provided.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your reproduction in order to make the bug happen?
        Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output / exception details.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
        You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
