name: Bug Report
description: Report a bug to help us improve.
labels: [🐛 bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the issue you encountered. [Github Issue Tracker](https://github.com/ChilliCream/graphql-platform/issues)
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which of our products is affected by this bug?
      options:
        - Hot Chocolate
        - Strawberry Shake
        - Banana Cake Pop
        - Green Donut
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        A list of steps that can be followed to recreate the bug.
        If it cannot be described in simple steps, create a GitHub repository with code that clearly showcases the described bug. Include a link to the repository in the box below.
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output / exception details.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Additional Context?
      description: |
        Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
        You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the selected product are you running?
      placeholder: "12.0.0"
    validations:
      required: true
