blank_issues_enabled: false
contact_links:
  - name: ChilliCream Community Support
    url: http://slack.chillicream.com/
    about: Join us on slack! We have a vibrant community that is helping each other.
  - name: ChilliCream Enterprise Support
    url: https://chillicream.com/services/support
    about: Get immediate access to a pool of ChilliCream experts which will support you along your journey.
  - name: ChilliCream Training
    url: https://chillicream.com/services/training
    about: Get your team trained in GraphQL, any of our products, and even React/Relay. Beginner Team? Advanced Team? Or Mixed? Don't panic! Our curriculum is designed to teach in-depth and works really well, but isn't set in stone.
  - name: ChilliCream Consulting
    url: https://chillicream.com/services/advisory
    about: Hourly consulting services to get the help you need at any stage of your project. This is the best way to get started.
