blank_issues_enabled: false
contact_links:
  - name: ChilliCream Community Support
    url: https://bit.ly/join-chillicream-slack
    about: Join us on slack! We have a vibrant community that is helping each other.
  - name: ChilliCream Enterprise Support
    url: https://chillicream.com/support
    about: Get immediate access to a pool of ChilliCream experts which will support you along your journey.
