blank_issues_enabled: false
contact_links:
  - name: ChilliCream Community Support
    url: https://bit.ly/joinchilli
    about: Please ask and answer questions here.
  - name: ChilliCream Enterprise Support
    url: https://chillicream.com/support
    about: Get immediate access to a pool of ChilliCream experts which will support you along your journey.
