<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CookieCrumble.Resources</AssemblyName>
    <RootNamespace>CookieCrumble.Resources</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

</Project>
