using ChilliCream.Nitro.Client.Telemetry.Models;

namespace ChilliCream.Nitro.CommandLine.Commands.Telemetry.Traces;

internal sealed record TraceJsonData(
    string Kind,
    string? Flavor,
    string? Method,
    string? Scheme,
    int? StatusCode,
    string? Url,
    string? UserAgent,
    string? ConnectionString,
    string? Instance,
    string? Name,
    string? Operation,
    string? Statement,
    string? System,
    string? User,
    GraphQLTraceDocument? Document,
    GraphQLTraceOperation? GraphQLOperation,
    GraphQLTraceSelection? Selection)
{
    public static TraceJsonData? From(TraceSpanData? data)
        => data switch
        {
            HttpTraceSpanData http => new(
                "http",
                http.Flavor,
                http.Method,
                http.Scheme,
                http.StatusCode,
                http.Url,
                http.UserAgent,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
            DatabaseTraceSpanData database => new(
                "database",
                null,
                null,
                null,
                null,
                database.Url,
                null,
                database.ConnectionString,
                database.Instance,
                database.Name,
                database.Operation,
                database.Statement,
                database.System,
                database.User,
                null,
                null,
                null),
            GraphQLOperationTraceSpanData graphQl => new(
                "graphql.operation",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                graphQl.Document,
                graphQl.Operation,
                null),
            GraphQLResolverTraceSpanData resolver => new(
                "graphql.resolver",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                resolver.Selection),
            _ => null
        };
}
