trigger:
  branches:
    include:
      - main

pr:
  - main

variables:
  CCT: $(CodeCovToken)

stages:
  - stage: ubuntu
    displayName: "Ubuntu 20.04"
    dependsOn: []
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: Test
        displayName: "Test"
        dependsOn: []
        continueOnError: true
        steps:
          - task: CmdLine@2
            displayName: "Run Tests"
            continueOnError: true
            inputs:
              script: './build.cmd Cover --skip --CodeCovToken $(CCT)'
          - task: PublishBuildArtifacts@1
            displayName: "Upload Test Results"
            inputs:
              artifactName: test-results
              pathtoPublish: "output/test-results"
