trigger: none

stages:
  - stage: release
    displayName: "Release"
    dependsOn: []
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: Pack
        displayName: "Pack"
        dependsOn: []
        steps:
          - task: DeleteFiles@1
            displayName: "Clean AspNetCore resources"
            inputs:
              SourceFolder: './src/HotChocolate/AspNetCore/src/AspNetCore/Resources'
              Contents: '**/*'
              RemoveDotFiles: true
          - task: DownloadPipelineArtifact@2
            displayName: "Integrate Banana Cake pop"
            inputs:
              buildType: 'specific'
              project: 'aefb2b59-b7d8-48cf-8cb0-30fdea720770'
              definition: '84'
              buildVersionToDownload: 'latest'
              artifactName: 'WebApp'
              targetPath: './src/HotChocolate/AspNetCore/src/AspNetCore/Resources'
          - task: PublishBuildArtifacts@1
            displayName: "Upload AspNetCore Code"
            inputs:
              artifactName: aspnetcore
              pathtoPublish: "./src/HotChocolate/AspNetCore/src/AspNetCore"
          - task: CmdLine@2
            displayName: "Create Packages"
            inputs:
              script: "./build.cmd pack"
          - task: PublishBuildArtifacts@1
            displayName: "Upload Packages"
            inputs:
              artifactName: packages
              pathtoPublish: "output/packages"
      - job: Publish
        displayName: "Publish"
        dependsOn: [Pack]
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Packages"
            inputs:
              artifactName: "packages"
              downloadPath: "$(Build.Repository.LocalPath)/output"
          - task: CmdLine@2
            displayName: "Push Packages to NuGet"
            inputs:
              script: "./build.cmd publish --skip"
          - task: GitHubRelease@0
            displayName: "Update GitHub Release"
            inputs:
              gitHubConnection: "ChilliCream GitHub"
              action: edit
              tag: "$(GitHubVersion)"
              title: "$(GitHubVersion)"
              assets: "$(Build.Repository.LocalPath)/output/packages/*.*"
              assetUploadMode: replace
              isPreRelease: true
              releaseNotesSource: input
              releaseNotes: "For more details click [here](https://github.com/ChilliCream/graphql-platform/blob/master/CHANGELOG.md) to get to our CHANGELOG."
