trigger:
  branches:
    include:
      - master
  tags:
    include:
      - 11.*

stages:
  - stage: ubuntu
    displayName: "Ubuntu 20.04"
    dependsOn: []
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: Sonar
        displayName: "Sonar"
        dependsOn: [ ]
        steps:
          - task: JavaToolInstaller@0
            displayName: "Install Java"
            inputs:
              versionSpec: "11"
              jdkArchitectureOption: "x64"
              jdkSourceOption: "PreInstalled"
              jdkDestinationDirectory: ./.java
          - task: CmdLine@2
            displayName: "Run Sonar Analysis"
            inputs:
              script: "./build.cmd Sonar"