trigger:
  branches:
    include:
      - master
  tags:
    include:
      - 11.*

stages:
  - stage: ubuntu
    displayName: "Ubuntu 20.04"
    dependsOn: []
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: Sonar
        displayName: "Sonar"
        dependsOn: [ ]
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET Core 2.1"
            inputs:
              packageType: 'sdk'
              version: '2.1.816'
          - task: UseDotNet@2
            displayName: "Install .NET Core 3.1"
            inputs:
              packageType: 'sdk'
              version: '3.1.409'
          - task: UseDotNet@2
            displayName: "Install .NET 5.0"
            inputs:
              packageType: 'sdk'
              version: '5.0.300'
          - task: UseDotNet@2
            displayName: "Install .NET Core"
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
          - task: JavaToolInstaller@0
            displayName: "Install Java"
            inputs:
              versionSpec: "11"
              jdkArchitectureOption: "x64"
              jdkSourceOption: "PreInstalled"
              jdkDestinationDirectory: ./.java
          - task: CmdLine@2
            displayName: "Run Sonar Analysis"
            inputs:
              script: "./build.cmd Sonar"