<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>FusionReleasePipeline.Gateway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ChilliCream.Nitro" />
    <PackageReference Include="ChilliCream.Nitro.Fusion" />
    <PackageReference Include="HotChocolate.Fusion.AspNetCore" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>
</Project>
