//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Validation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotChocolate.Validation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema name is mandatory in order to create a validator..
        /// </summary>
        internal static string DefaultDocumentValidatorFactory_Schema_Name_Is_Mandatory {
            get {
                return ResourceManager.GetString("DefaultDocumentValidatorFactory_Schema_Name_Is_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has an invalid state and is missing the schema..
        /// </summary>
        internal static string DocumentValidatorContext_Context_Invalid_State {
            get {
                return ResourceManager.GetString("DocumentValidatorContext_Context_Invalid_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument `{0}` does not exist..
        /// </summary>
        internal static string ErrorHelper_ArgumentDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorHelper_ArgumentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one argument with the same name in an argument set is ambiguous and invalid..
        /// </summary>
        internal static string ErrorHelper_ArgumentNotUnique {
            get {
                return ResourceManager.GetString("ErrorHelper_ArgumentNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument `{0}` is required..
        /// </summary>
        internal static string ErrorHelper_ArgumentRequired {
            get {
                return ResourceManager.GetString("ErrorHelper_ArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument value does not match the argument type..
        /// </summary>
        internal static string ErrorHelper_ArgumentValueIsNotCompatible {
            get {
                return ResourceManager.GetString("ErrorHelper_ArgumentValueIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directive `{0}` is not supported by the current schema..
        /// </summary>
        internal static string ErrorHelper_DirectiveNotSupported {
            get {
                return ResourceManager.GetString("ErrorHelper_DirectiveNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directive is not valid the current location..
        /// </summary>
        internal static string ErrorHelper_DirectiveNotValidInLocation {
            get {
                return ResourceManager.GetString("ErrorHelper_DirectiveNotValidInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field `{0}` does not exist on the type `{1}`..
        /// </summary>
        internal static string ErrorHelper_FieldDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorHelper_FieldDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is a required field and cannot be null..
        /// </summary>
        internal static string ErrorHelper_FieldIsRequiredButNull {
            get {
                return ResourceManager.GetString("ErrorHelper_FieldIsRequiredButNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered fields for the same object that cannot be merged..
        /// </summary>
        internal static string ErrorHelper_FieldsAreNotMergable {
            get {
                return ResourceManager.GetString("ErrorHelper_FieldsAreNotMergable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value type of field `{0}` does not match the field type..
        /// </summary>
        internal static string ErrorHelper_FieldValueIsNotCompatible {
            get {
                return ResourceManager.GetString("ErrorHelper_FieldValueIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph of fragment spreads must not form any cycles including spreading itself. Otherwise an operation could infinitely spread or infinitely execute on cycles in the underlying data..
        /// </summary>
        internal static string ErrorHelper_FragmentCycleDetected {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentCycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified fragment `{0}` does not exist..
        /// </summary>
        internal static string ErrorHelper_FragmentDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple fragments with the name `{0}`..
        /// </summary>
        internal static string ErrorHelper_FragmentNameNotUnique {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent type does not match the type condition on the fragment..
        /// </summary>
        internal static string ErrorHelper_FragmentNotPossible {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified fragment `{0}` is not used within the current document..
        /// </summary>
        internal static string ErrorHelper_FragmentNotUsed {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragments can only be declared on unions, interfaces, and objects..
        /// </summary>
        internal static string ErrorHelper_FragmentOnlyCompositeType {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentOnlyCompositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type `{0}`..
        /// </summary>
        internal static string ErrorHelper_FragmentTypeConditionUnknown {
            get {
                return ResourceManager.GetString("ErrorHelper_FragmentTypeConditionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be only one input field named `{0}`..
        /// </summary>
        internal static string ErrorHelper_InputFieldAmbiguous {
            get {
                return ResourceManager.GetString("ErrorHelper_InputFieldAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified input object field `{0}` does not exist..
        /// </summary>
        internal static string ErrorHelper_InputFieldDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorHelper_InputFieldDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is a required field and cannot be null..
        /// </summary>
        internal static string ErrorHelper_InputFieldRequired {
            get {
                return ResourceManager.GetString("ErrorHelper_InputFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` returns {1} value. Selections on scalars or enums are never allowed, because they are the leaf nodes of any GraphQL query..
        /// </summary>
        internal static string ErrorHelper_LeafFieldsCannotHaveSelections {
            get {
                return ResourceManager.GetString("ErrorHelper_LeafFieldsCannotHaveSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GraphQL document has an operation complexity of {0} which exceeds the max allowed operation complexity of {1}..
        /// </summary>
        internal static string ErrorHelper_MaxOperationComplexity {
            get {
                return ResourceManager.GetString("ErrorHelper_MaxOperationComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is an object, interface or union type field. Leaf selections on objects, interfaces, and unions without subfields are disallowed..
        /// </summary>
        internal static string ErrorHelper_NoSelectionOnCompositeField {
            get {
                return ResourceManager.GetString("ErrorHelper_NoSelectionOnCompositeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphQL allows a short‐hand form for defining query operations when only that one operation exists in the document..
        /// </summary>
        internal static string ErrorHelper_OperationAnonymousMoreThanOne {
            get {
                return ResourceManager.GetString("ErrorHelper_OperationAnonymousMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation name `{0}` is not unique..
        /// </summary>
        internal static string ErrorHelper_OperationNameNotUnique {
            get {
                return ResourceManager.GetString("ErrorHelper_OperationNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription operations must have exactly one root field..
        /// </summary>
        internal static string ErrorHelper_SubscriptionSingleRootField {
            get {
                return ResourceManager.GetString("ErrorHelper_SubscriptionSingleRootField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document containing TypeSystemDefinition is invalid for execution..
        /// </summary>
        internal static string ErrorHelper_TypeSystemDefinitionNotAllowed {
            get {
                return ResourceManager.GetString("ErrorHelper_TypeSystemDefinitionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A union type cannot declare a field directly. Use inline fragments or fragments instead..
        /// </summary>
        internal static string ErrorHelper_UnionFieldError {
            get {
                return ResourceManager.GetString("ErrorHelper_UnionFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value type of variable `{0}` does not match the variable type..
        /// </summary>
        internal static string ErrorHelper_VariableDefaultValueIsNotCompatible {
            get {
                return ResourceManager.GetString("ErrorHelper_VariableDefaultValueIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable `{0}` is not compatible with the type of the current location..
        /// </summary>
        internal static string ErrorHelper_VariableIsNotCompatible {
            get {
                return ResourceManager.GetString("ErrorHelper_VariableIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document containing operations that define more than one variable with the same name is invalid for execution..
        /// </summary>
        internal static string ErrorHelper_VariableNameNotUnique {
            get {
                return ResourceManager.GetString("ErrorHelper_VariableNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of variable `{0}` is not an input type..
        /// </summary>
        internal static string ErrorHelper_VariableNotInputType {
            get {
                return ResourceManager.GetString("ErrorHelper_VariableNotInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema name is mandatory in order to add validation rules..
        /// </summary>
        internal static string ServiceCollectionExtensions_Schema_Name_Is_Mandatory {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_Schema_Name_Is_Mandatory", resourceCulture);
            }
        }
        
        internal static string HotChocolateValidationBuilderExtensions_MinimumAllowedValue {
            get {
                return ResourceManager.GetString("HotChocolateValidationBuilderExtensions_MinimumAllowedValue", resourceCulture);
            }
        }
    }
}
