namespace Mocha;

/// <summary>
/// Configuration for a topology resource, linking it to its parent <see cref="MessagingTopology"/>.
/// </summary>
public class TopologyConfiguration : MessagingConfiguration
{
    /// <summary>
    /// Gets or sets the messaging topology that owns this resource.
    /// </summary>
    public MessagingTopology? Topology { get; set; }

    /// <summary>
    /// Gets or sets the origin of this topology item, indicating whether it was declared explicitly
    /// by the user or generated by the framework. When <c>null</c>, convention is assumed.
    /// </summary>
    public string? Origin { get; set; }
}
