<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ChilliCream.Nitro.Fusion</AssemblyName>
    <RootNamespace>ChilliCream.Nitro.Fusion</RootNamespace>
    <TargetFrameworks>net11.0;net10.0;net9.0</TargetFrameworks>
    <IsAotCompatible>false</IsAotCompatible>
    <Description>Provides deterministic Nitro upload and publication workflows for Hot Chocolate Fusion.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ChilliCream.Nitro.Fusion.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\StrawberryShake\Client\src\Core\StrawberryShake.Core.csproj" />
    <ProjectReference Include="..\..\..\..\StrawberryShake\Client\src\Transport.Http\StrawberryShake.Transport.Http.csproj" />
    <ProjectReference Include="..\..\..\..\HotChocolate\Fusion\src\Fusion.SourceSchema.Packaging\HotChocolate.Fusion.SourceSchema.Packaging.csproj" />
    <ProjectReference Include="..\..\..\..\HotChocolate\Language\src\Language.SyntaxTree\HotChocolate.Language.SyntaxTree.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
