//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Fusion.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompositionResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompositionResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Fusion.Properties.CompositionResources", typeof(CompositionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorHelper_PostMergeValidationFailed {
            get {
                return ResourceManager.GetString("ErrorHelper_PostMergeValidationFailed", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_PreMergeValidationFailed {
            get {
                return ResourceManager.GetString("ErrorHelper_PreMergeValidationFailed", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_SatisfiabilityValidationFailed {
            get {
                return ResourceManager.GetString("ErrorHelper_SatisfiabilityValidationFailed", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_SourceSchemaParsingFailed {
            get {
                return ResourceManager.GetString("ErrorHelper_SourceSchemaParsingFailed", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_SourceSchemaValidationFailed {
            get {
                return ResourceManager.GetString("ErrorHelper_SourceSchemaValidationFailed", resourceCulture);
            }
        }
        
        internal static string ExternalMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("ExternalMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionEnumValueMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionEnumValueMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionEnumValueMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionEnumValueMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldDefinitionMutableScalarTypeDefinition_Description {
            get {
                return ResourceManager.GetString("FusionFieldDefinitionMutableScalarTypeDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldMutableDirectiveDefinition_Argument_Partial_Description {
            get {
                return ResourceManager.GetString("FusionFieldMutableDirectiveDefinition_Argument_Partial_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldMutableDirectiveDefinition_Argument_Provides_Description {
            get {
                return ResourceManager.GetString("FusionFieldMutableDirectiveDefinition_Argument_Provides_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionFieldMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldMutableDirectiveDefinition_Argument_SourceType_Description {
            get {
                return ResourceManager.GetString("FusionFieldMutableDirectiveDefinition_Argument_SourceType_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionFieldMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldSelectionMapMutableScalarTypeDefinition_Description {
            get {
                return ResourceManager.GetString("FusionFieldSelectionMapMutableScalarTypeDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldSelectionPathMutableScalarTypeDefinition_Description {
            get {
                return ResourceManager.GetString("FusionFieldSelectionPathMutableScalarTypeDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionFieldSelectionSetMutableScalarTypeDefinition_Description {
            get {
                return ResourceManager.GetString("FusionFieldSelectionSetMutableScalarTypeDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionImplementsMutableDirectiveDefinition_Argument_Interface_Description {
            get {
                return ResourceManager.GetString("FusionImplementsMutableDirectiveDefinition_Argument_Interface_Description", resourceCulture);
            }
        }
        
        internal static string FusionImplementsMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionImplementsMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionImplementsMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionImplementsMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionInaccessibleMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionInaccessibleMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionInputFieldMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionInputFieldMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionInputFieldMutableDirectiveDefinition_Argument_SourceType_Description {
            get {
                return ResourceManager.GetString("FusionInputFieldMutableDirectiveDefinition_Argument_SourceType_Description", resourceCulture);
            }
        }
        
        internal static string FusionInputFieldMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionInputFieldMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Field_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Field_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Internal_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Internal_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Key_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Key_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Map_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Map_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Path_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Path_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionLookupMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionLookupMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionRequiresMutableDirectiveDefinition_Field_Description {
            get {
                return ResourceManager.GetString("FusionRequiresMutableDirectiveDefinition_Field_Description", resourceCulture);
            }
        }
        
        internal static string FusionRequiresMutableDirectiveDefinition_Map_Description {
            get {
                return ResourceManager.GetString("FusionRequiresMutableDirectiveDefinition_Map_Description", resourceCulture);
            }
        }
        
        internal static string FusionRequiresMutableDirectiveDefinition_Requirements_Description {
            get {
                return ResourceManager.GetString("FusionRequiresMutableDirectiveDefinition_Requirements_Description", resourceCulture);
            }
        }
        
        internal static string FusionRequiresMutableDirectiveDefinition_Schema_Description {
            get {
                return ResourceManager.GetString("FusionRequiresMutableDirectiveDefinition_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionRequiresMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionRequiresMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionSchemaMetadataMutableDirectiveDefinition_Argument_Name_Description {
            get {
                return ResourceManager.GetString("FusionSchemaMetadataMutableDirectiveDefinition_Argument_Name_Description", resourceCulture);
            }
        }
        
        internal static string FusionSchemaMetadataMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionSchemaMetadataMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionSchemaMutableEnumTypeDefinition_Description {
            get {
                return ResourceManager.GetString("FusionSchemaMutableEnumTypeDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionTypeMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionTypeMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionTypeMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionTypeMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string FusionUnionMemberMutableDirectiveDefinition_Argument_Member_Description {
            get {
                return ResourceManager.GetString("FusionUnionMemberMutableDirectiveDefinition_Argument_Member_Description", resourceCulture);
            }
        }
        
        internal static string FusionUnionMemberMutableDirectiveDefinition_Argument_Schema_Description {
            get {
                return ResourceManager.GetString("FusionUnionMemberMutableDirectiveDefinition_Argument_Schema_Description", resourceCulture);
            }
        }
        
        internal static string FusionUnionMemberMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("FusionUnionMemberMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string InaccessibleMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("InaccessibleMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string InternalMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("InternalMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string IsMutableDirectiveDefinition_Argument_Field_Description {
            get {
                return ResourceManager.GetString("IsMutableDirectiveDefinition_Argument_Field_Description", resourceCulture);
            }
        }
        
        internal static string IsMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("IsMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string KeyMutableDirectiveDefinition_Argument_Fields_Description {
            get {
                return ResourceManager.GetString("KeyMutableDirectiveDefinition_Argument_Fields_Description", resourceCulture);
            }
        }
        
        internal static string KeyMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("KeyMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_DisallowedInaccessibleBuiltInScalar {
            get {
                return ResourceManager.GetString("LogEntryHelper_DisallowedInaccessibleBuiltInScalar", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_DisallowedInaccessibleIntrospectionType {
            get {
                return ResourceManager.GetString("LogEntryHelper_DisallowedInaccessibleIntrospectionType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_DisallowedInaccessibleIntrospectionField {
            get {
                return ResourceManager.GetString("LogEntryHelper_DisallowedInaccessibleIntrospectionField", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_DisallowedInaccessibleIntrospectionArgument {
            get {
                return ResourceManager.GetString("LogEntryHelper_DisallowedInaccessibleIntrospectionArgument", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_DisallowedInaccessibleDirectiveArgument {
            get {
                return ResourceManager.GetString("LogEntryHelper_DisallowedInaccessibleDirectiveArgument", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EmptyMergedEnumType {
            get {
                return ResourceManager.GetString("LogEntryHelper_EmptyMergedEnumType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EmptyMergedInputObjectType {
            get {
                return ResourceManager.GetString("LogEntryHelper_EmptyMergedInputObjectType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EmptyMergedInterfaceType {
            get {
                return ResourceManager.GetString("LogEntryHelper_EmptyMergedInterfaceType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EmptyMergedObjectType {
            get {
                return ResourceManager.GetString("LogEntryHelper_EmptyMergedObjectType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EmptyMergedUnionType {
            get {
                return ResourceManager.GetString("LogEntryHelper_EmptyMergedUnionType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EnumTypeDefaultValueInaccessible {
            get {
                return ResourceManager.GetString("LogEntryHelper_EnumTypeDefaultValueInaccessible", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_EnumValuesMismatch {
            get {
                return ResourceManager.GetString("LogEntryHelper_EnumValuesMismatch", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ExternalArgumentDefaultMismatch {
            get {
                return ResourceManager.GetString("LogEntryHelper_ExternalArgumentDefaultMismatch", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ExternalMissingOnBase {
            get {
                return ResourceManager.GetString("LogEntryHelper_ExternalMissingOnBase", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ExternalOnInterface {
            get {
                return ResourceManager.GetString("LogEntryHelper_ExternalOnInterface", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ExternalUnused {
            get {
                return ResourceManager.GetString("LogEntryHelper_ExternalUnused", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_FieldArgumentTypesNotMergeable {
            get {
                return ResourceManager.GetString("LogEntryHelper_FieldArgumentTypesNotMergeable", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_FieldWithMissingRequiredArgument {
            get {
                return ResourceManager.GetString("LogEntryHelper_FieldWithMissingRequiredArgument", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ImplementedByInaccessible {
            get {
                return ResourceManager.GetString("LogEntryHelper_ImplementedByInaccessible", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InputFieldDefaultMismatch {
            get {
                return ResourceManager.GetString("LogEntryHelper_InputFieldDefaultMismatch", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InputFieldTypesNotMergeable {
            get {
                return ResourceManager.GetString("LogEntryHelper_InputFieldTypesNotMergeable", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InputWithMissingRequiredFields {
            get {
                return ResourceManager.GetString("LogEntryHelper_InputWithMissingRequiredFields", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InterfaceFieldNoImplementation {
            get {
                return ResourceManager.GetString("LogEntryHelper_InterfaceFieldNoImplementation", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InvalidGraphQL {
            get {
                return ResourceManager.GetString("LogEntryHelper_InvalidGraphQL", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_InvalidShareableUsage {
            get {
                return ResourceManager.GetString("LogEntryHelper_InvalidShareableUsage", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_IsInvalidField {
            get {
                return ResourceManager.GetString("LogEntryHelper_IsInvalidField", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_IsInvalidFieldType {
            get {
                return ResourceManager.GetString("LogEntryHelper_IsInvalidFieldType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_IsInvalidSyntax {
            get {
                return ResourceManager.GetString("LogEntryHelper_IsInvalidSyntax", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_IsInvalidUsage {
            get {
                return ResourceManager.GetString("LogEntryHelper_IsInvalidUsage", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyDirectiveInFieldsArgument {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyDirectiveInFieldsArgument", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyFieldsHasArguments {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyFieldsHasArguments", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyFieldsSelectInvalidType {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyFieldsSelectInvalidType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyInvalidFields {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyInvalidFields", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyInvalidFieldsType {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyInvalidFieldsType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_KeyInvalidSyntax {
            get {
                return ResourceManager.GetString("LogEntryHelper_KeyInvalidSyntax", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_LookupReturnsList {
            get {
                return ResourceManager.GetString("LogEntryHelper_LookupReturnsList", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_LookupReturnsNonNullableType {
            get {
                return ResourceManager.GetString("LogEntryHelper_LookupReturnsNonNullableType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_NonNullInputFieldIsInaccessible {
            get {
                return ResourceManager.GetString("LogEntryHelper_NonNullInputFieldIsInaccessible", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_NoQueries {
            get {
                return ResourceManager.GetString("LogEntryHelper_NoQueries", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_OutputFieldTypesNotMergeable {
            get {
                return ResourceManager.GetString("LogEntryHelper_OutputFieldTypesNotMergeable", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_OverrideFromSelf {
            get {
                return ResourceManager.GetString("LogEntryHelper_OverrideFromSelf", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_OverrideOnInterface {
            get {
                return ResourceManager.GetString("LogEntryHelper_OverrideOnInterface", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesDirectiveInFieldsArgument {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesDirectiveInFieldsArgument", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesFieldsHasArguments {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesFieldsHasArguments", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesFieldsMissingExternal {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesFieldsMissingExternal", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesInvalidFields {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesInvalidFields", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesInvalidFieldsType {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesInvalidFieldsType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesInvalidSyntax {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesInvalidSyntax", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_ProvidesOnNonCompositeField {
            get {
                return ResourceManager.GetString("LogEntryHelper_ProvidesOnNonCompositeField", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_QueryRootTypeInaccessible {
            get {
                return ResourceManager.GetString("LogEntryHelper_QueryRootTypeInaccessible", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RequireInvalidFields {
            get {
                return ResourceManager.GetString("LogEntryHelper_RequireInvalidFields", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RequireInvalidFieldType {
            get {
                return ResourceManager.GetString("LogEntryHelper_RequireInvalidFieldType", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RequireInvalidSyntax {
            get {
                return ResourceManager.GetString("LogEntryHelper_RequireInvalidSyntax", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RootMutationUsed {
            get {
                return ResourceManager.GetString("LogEntryHelper_RootMutationUsed", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RootQueryUsed {
            get {
                return ResourceManager.GetString("LogEntryHelper_RootQueryUsed", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_RootSubscriptionUsed {
            get {
                return ResourceManager.GetString("LogEntryHelper_RootSubscriptionUsed", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_TypeDefinitionInvalid {
            get {
                return ResourceManager.GetString("LogEntryHelper_TypeDefinitionInvalid", resourceCulture);
            }
        }
        
        internal static string LogEntryHelper_TypeKindMismatch {
            get {
                return ResourceManager.GetString("LogEntryHelper_TypeKindMismatch", resourceCulture);
            }
        }
        
        internal static string LookupMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("LookupMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string OverrideMutableDirectiveDefinition_Argument_From_Description {
            get {
                return ResourceManager.GetString("OverrideMutableDirectiveDefinition_Argument_From_Description", resourceCulture);
            }
        }
        
        internal static string OverrideMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("OverrideMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string ProvidesMutableDirectiveDefinition_Argument_Fields_Description {
            get {
                return ResourceManager.GetString("ProvidesMutableDirectiveDefinition_Argument_Fields_Description", resourceCulture);
            }
        }
        
        internal static string ProvidesMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("ProvidesMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_CycleDetected {
            get {
                return ResourceManager.GetString("RequirementsValidator_CycleDetected", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_FieldDoesNotExistOnType {
            get {
                return ResourceManager.GetString("RequirementsValidator_FieldDoesNotExistOnType", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_NoLookupsFoundForType {
            get {
                return ResourceManager.GetString("RequirementsValidator_NoLookupsFoundForType", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_NoOtherSchemasContainField {
            get {
                return ResourceManager.GetString("RequirementsValidator_NoOtherSchemasContainField", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_UnableToAccessFieldOnPath {
            get {
                return ResourceManager.GetString("RequirementsValidator_UnableToAccessFieldOnPath", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_UnableToSatisfyRequirement {
            get {
                return ResourceManager.GetString("RequirementsValidator_UnableToSatisfyRequirement", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_UnableToSatisfyRequirementForLookup {
            get {
                return ResourceManager.GetString("RequirementsValidator_UnableToSatisfyRequirementForLookup", resourceCulture);
            }
        }
        
        internal static string RequirementsValidator_UnableToTransitionBetweenSchemas {
            get {
                return ResourceManager.GetString("RequirementsValidator_UnableToTransitionBetweenSchemas", resourceCulture);
            }
        }
        
        internal static string RequireMutableDirectiveDefinition_Argument_Field_Description {
            get {
                return ResourceManager.GetString("RequireMutableDirectiveDefinition_Argument_Field_Description", resourceCulture);
            }
        }
        
        internal static string RequireMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("RequireMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_CycleDetected {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_CycleDetected", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_NodeTypeHasNoNodeLookup {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_NodeTypeHasNoNodeLookup", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_NoLookupsFoundForType {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_NoLookupsFoundForType", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_UnableToAccessFieldOnPath {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_UnableToAccessFieldOnPath", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_UnableToSatisfyRequirement {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_UnableToSatisfyRequirement", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_UnableToSatisfyRequirementForLookup {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_UnableToSatisfyRequirementForLookup", resourceCulture);
            }
        }
        
        internal static string SatisfiabilityValidator_UnableToTransitionBetweenSchemas {
            get {
                return ResourceManager.GetString("SatisfiabilityValidator_UnableToTransitionBetweenSchemas", resourceCulture);
            }
        }
        
        internal static string SchemaNameMutableDirectiveDefinition_Argument_Value_Description {
            get {
                return ResourceManager.GetString("SchemaNameMutableDirectiveDefinition_Argument_Value_Description", resourceCulture);
            }
        }
        
        internal static string SchemaNameMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("SchemaNameMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string ShareableMutableDirectiveDefinition_Description {
            get {
                return ResourceManager.GetString("ShareableMutableDirectiveDefinition_Description", resourceCulture);
            }
        }
        
        internal static string TypeDefinitionExtensions_TheSpecifiedTypeIsNotAnAbstractType {
            get {
                return ResourceManager.GetString("TypeDefinitionExtensions_TheSpecifiedTypeIsNotAnAbstractType", resourceCulture);
            }
        }
        
        internal static string TypeDefinitionInvalidRule_ArgumentMissing {
            get {
                return ResourceManager.GetString("TypeDefinitionInvalidRule_ArgumentMissing", resourceCulture);
            }
        }
        
        internal static string TypeDefinitionInvalidRule_ArgumentTypeDifferent {
            get {
                return ResourceManager.GetString("TypeDefinitionInvalidRule_ArgumentTypeDifferent", resourceCulture);
            }
        }
    }
}
