namespace HotChocolate.Fusion.Execution.Clients;

/// <summary>
/// Describes a single lookup field on the composite schema that maps
/// to an Apollo Federation entity type. Used by <see cref="FederationQueryRewriter"/>
/// to detect entity lookups and rewrite them into <c>_entities</c> queries.
/// </summary>
internal sealed class LookupFieldInfo
{
    /// <summary>
    /// Gets the entity type name this lookup resolves (e.g. <c>"Product"</c>).
    /// </summary>
    public required string EntityTypeName { get; init; }

    /// <summary>
    /// Maps argument name (e.g. <c>"id"</c>) to entity key field name (e.g. <c>"id"</c>).
    /// </summary>
    public required IReadOnlyDictionary<string, string> ArgumentToKeyFieldMap { get; init; }
}

/// <summary>
/// Describes the <c>@require(field: ...)</c> arguments declared on the fields
/// of a single entity type. For every entity field that carries synthetic
/// <c>@require</c> arguments (generated by the composer from
/// <c>@requires(fields: ...)</c> on the owning subgraph), this maps the
/// argument name to the entity-representation field path that the Apollo
/// Federation runtime expects to receive on the <c>_entities</c>
/// representation.
/// <para>
/// The rewriter uses this to strip the <c>@require</c> arguments from the
/// inline-fragment <c>FieldNode</c> at the lookup-field selection and to
/// record a variable-to-representation mapping that <see cref="ApolloFederationSourceSchemaClient"/>
/// merges into the outgoing representation body.
/// </para>
/// </summary>
internal sealed class EntityRequiresInfo
{
    /// <summary>
    /// Maps entity field name (e.g. <c>"isExpensive"</c>) to a dictionary of
    /// argument name (e.g. <c>"price"</c>) to require field path
    /// (e.g. <c>"price"</c>).
    /// </summary>
    public required IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Fields { get; init; }
}
