using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using HotChocolate.Execution;
using HotChocolate.Language;
using HotChocolate.Resolvers;
using HotChocolate.Stitching.Execution;
using HotChocolate.Stitching.Processing.ScopedVariables;
using HotChocolate.Stitching.Properties;
using HotChocolate.Stitching.Utilities;
using HotChocolate.Types;
using static HotChocolate.Stitching.Processing.DelegationHelpers;
using static HotChocolate.Stitching.WellKnownContextData;

namespace HotChocolate.Stitching.Processing;

internal sealed class QueryResultMiddleware
{
    private readonly FieldDelegate _next;

    public QueryResultMiddleware(FieldDelegate next)
    {
        _next = next ?? throw new ArgumentNullException(nameof(next));
    }

    public async Task InvokeAsync(IMiddlewareContext context)
    {
        if (context.Result is IQueryResult result &&
            context.ScopedContextData.TryGetValue(SchemaName, out var targetSchemaValue) &&
            context.ScopedContextData.TryGetValue(WellKnownContextData.Path, out var pathValue) &&
            context.ScopedContextData.TryGetValue(ReversePath, out var reversePathValue) &&
            targetSchemaValue is NameString targetSchema &&
            pathValue is IImmutableStack<SelectionPathComponent> path &&
            reversePathValue is IImmutableStack<SelectionPathComponent> reversePath)
        {
            context.RegisterForCleanup(result.Dispose);
            CopyResultContextData(context, result);

            var value = ExtractData(result.Data, reversePath, context.ResponseName);
            context.Result = value is null or NullValueNode ? null : new SerializedData(value);
            if (result.Errors is not null)
            {
                ReportErrors(targetSchema, context, path, result.Errors);
            }
        }

        await _next.Invoke(context).ConfigureAwait(false);
    }

    private static void CopyResultContextData(IResolverContext context, IExecutionResult result)
    {
        if (result.ContextData is { Count: > 0 })
        {
            ImmutableDictionary<string, object?>.Builder builder =
                ImmutableDictionary.CreateBuilder<string, object?>();
            builder.AddRange(context.ScopedContextData);
            builder.AddRange(result.ContextData);
            context.ScopedContextData = builder.ToImmutableDictionary();
        }
    }

    private static IQueryRequest CreateQuery(
        IMiddlewareContext context,
        NameString schemaName,
        IImmutableStack<SelectionPathComponent> path,
        IImmutableStack<SelectionPathComponent> reversePath)
    {
        var fieldRewriter = new ExtractFieldQuerySyntaxRewriter(
            context.Schema,
            context.Service<IEnumerable<IQueryDelegationRewriter>>());

        OperationType operationType =
            context.Schema.IsRootType(context.ObjectType)
                ? context.Operation.Operation
                : OperationType.Query;

        ExtractedField extractedField = fieldRewriter.ExtractField(
            schemaName, context.Document, context.Operation,
            context.Selection, context.ObjectType);

        IEnumerable<ScopedVariableValue> scopedVariables =
            ResolveScopedVariables(
                context, schemaName, operationType,
                reversePath, fieldRewriter);

        IReadOnlyCollection<ScopedVariableValue> variableValues =
            CreateVariableValues(
                context, schemaName, scopedVariables,
                extractedField, fieldRewriter);

        RemoteQueryBuilder builder =
            RemoteQueryBuilder.New()
                .SetRequestField(extractedField.SyntaxNodes[0])
                .SetOperation(context.Operation.Name, operationType)
                .SetSelectionPath(path)
                .AddVariables(CreateVariableDefs(variableValues))
                .AddFragmentDefinitions(extractedField.Fragments);

        if (extractedField.SyntaxNodes.Count > 1)
        {
            for (var i = 1; i < extractedField.SyntaxNodes.Count; i++)
            {
                builder.AddAdditionalField(extractedField.SyntaxNodes[i]);
            }
        }

        DocumentNode query = builder.Build(schemaName, context.Schema.GetNameLookup());

        var requestBuilder = QueryRequestBuilder.New();

        AddVariables(requestBuilder, query, variableValues);

        requestBuilder
            .SetQuery(query)
            .AddProperty(IsAutoGenerated, true);

        ObjectType rootType = context.Schema.GetOperationType(operationType)!;
        if (IsBatchableRequest(rootType, extractedField, path))
        {
            requestBuilder.TryAddProperty(IsBatchable, true);
        }

        return requestBuilder.Create();
    }

    private static bool IsBatchableRequest(
        ObjectType rootType,
        ExtractedField extractedField,
        IImmutableStack<SelectionPathComponent> path)
    {
        if (path.IsEmpty)
        {
            foreach (FieldNode field in extractedField.SyntaxNodes)
            {
                if (rootType.Fields.TryGetField(field.Name.Value, out ObjectField? rootField) &&
                    rootField.Type.Kind == TypeKind.NonNull)
                {
                    return false;
                }
            }
        }
        else
        {
            if (rootType.Fields.TryGetField(path.Peek().Name.Value, out ObjectField? rootField) &&
                rootField.Type.Kind == TypeKind.NonNull)
            {
                return false;
            }
        }

        return true;
    }
}
