//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Types.Scalars {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurrencyCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotChocolate.Types.Scalars.CurrencyCodes", typeof(CurrencyCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-AE.
        /// </summary>
        internal static string AED_784 {
            get {
                return ResourceManager.GetString("AED|784", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|uz-Arab-AF.
        /// </summary>
        internal static string AFN_971 {
            get {
                return ResourceManager.GetString("AFN|971", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sq-XK.
        /// </summary>
        internal static string ALL_008 {
            get {
                return ResourceManager.GetString("ALL|008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|hy-AM.
        /// </summary>
        internal static string AMD_051 {
            get {
                return ResourceManager.GetString("AMD|051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|nl-CW|nl-SX.
        /// </summary>
        internal static string ANG_532 {
            get {
                return ResourceManager.GetString("ANG|532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|pt-AO.
        /// </summary>
        internal static string AOA_973 {
            get {
                return ResourceManager.GetString("AOA|973", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-AR.
        /// </summary>
        internal static string ARS_032 {
            get {
                return ResourceManager.GetString("ARS|032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-AU|en-CX|en-CC|en-KI|en-NR|en-NF|en-TV.
        /// </summary>
        internal static string AUD_036 {
            get {
                return ResourceManager.GetString("AUD|036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|nl-AW.
        /// </summary>
        internal static string AWG_533 {
            get {
                return ResourceManager.GetString("AWG|533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|az-Latn-AZ.
        /// </summary>
        internal static string AZN_944 {
            get {
                return ResourceManager.GetString("AZN|944", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sr-Latn-BA.
        /// </summary>
        internal static string BAM_977 {
            get {
                return ResourceManager.GetString("BAM|977", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-BB.
        /// </summary>
        internal static string BBD_052 {
            get {
                return ResourceManager.GetString("BBD|052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ccp-Cakm-BD.
        /// </summary>
        internal static string BDT_050 {
            get {
                return ResourceManager.GetString("BDT|050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|bg-BG.
        /// </summary>
        internal static string BGN_975 {
            get {
                return ResourceManager.GetString("BGN|975", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|ar-BH.
        /// </summary>
        internal static string BHD_048 {
            get {
                return ResourceManager.GetString("BHD|048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|rn-BI.
        /// </summary>
        internal static string BIF_108 {
            get {
                return ResourceManager.GetString("BIF|108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-BM.
        /// </summary>
        internal static string BMD_060 {
            get {
                return ResourceManager.GetString("BMD|060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ms-BN.
        /// </summary>
        internal static string BND_096 {
            get {
                return ResourceManager.GetString("BND|096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|quz-BO.
        /// </summary>
        internal static string BOB_068 {
            get {
                return ResourceManager.GetString("BOB|068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|quz-BO.
        /// </summary>
        internal static string BOV_984 {
            get {
                return ResourceManager.GetString("BOV|984", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|pt-BR.
        /// </summary>
        internal static string BRL_986 {
            get {
                return ResourceManager.GetString("BRL|986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-BS.
        /// </summary>
        internal static string BSD_044 {
            get {
                return ResourceManager.GetString("BSD|044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|dz-BT.
        /// </summary>
        internal static string BTN_064 {
            get {
                return ResourceManager.GetString("BTN|064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tn-BW.
        /// </summary>
        internal static string BWP_072 {
            get {
                return ResourceManager.GetString("BWP|072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ru-BY.
        /// </summary>
        internal static string BYN_933 {
            get {
                return ResourceManager.GetString("BYN|933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-BZ.
        /// </summary>
        internal static string BZD_084 {
            get {
                return ResourceManager.GetString("BZD|084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|iu-Latn-CA.
        /// </summary>
        internal static string CAD_124 {
            get {
                return ResourceManager.GetString("CAD|124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CDF_976 {
            get {
                return ResourceManager.GetString("CDF|976", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|wae-CH.
        /// </summary>
        internal static string CHE_947 {
            get {
                return ResourceManager.GetString("CHE|947", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|wae-CH|gsw-LI.
        /// </summary>
        internal static string CHF_756 {
            get {
                return ResourceManager.GetString("CHF|756", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|wae-CH.
        /// </summary>
        internal static string CHW_948 {
            get {
                return ResourceManager.GetString("CHW|948", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4|es-CL.
        /// </summary>
        internal static string CLF_990 {
            get {
                return ResourceManager.GetString("CLF|990", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|es-CL.
        /// </summary>
        internal static string CLP_152 {
            get {
                return ResourceManager.GetString("CLP|152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CNY_156 {
            get {
                return ResourceManager.GetString("CNY|156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-CO.
        /// </summary>
        internal static string COP_170 {
            get {
                return ResourceManager.GetString("COP|170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-CO.
        /// </summary>
        internal static string COU_970 {
            get {
                return ResourceManager.GetString("COU|970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-CR.
        /// </summary>
        internal static string CRC_188 {
            get {
                return ResourceManager.GetString("CRC|188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-CU.
        /// </summary>
        internal static string CUC_931 {
            get {
                return ResourceManager.GetString("CUC|931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-CU.
        /// </summary>
        internal static string CUP_192 {
            get {
                return ResourceManager.GetString("CUP|192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|pt-CV.
        /// </summary>
        internal static string CVE_132 {
            get {
                return ResourceManager.GetString("CVE|132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CZK_203 {
            get {
                return ResourceManager.GetString("CZK|203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|so-DJ.
        /// </summary>
        internal static string DJF_262 {
            get {
                return ResourceManager.GetString("DJF|262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|fo-DK|fo-FO|kl-GL.
        /// </summary>
        internal static string DKK_208 {
            get {
                return ResourceManager.GetString("DKK|208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-DO.
        /// </summary>
        internal static string DOP_214 {
            get {
                return ResourceManager.GetString("DOP|214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tzm-Latn-DZ.
        /// </summary>
        internal static string DZD_012 {
            get {
                return ResourceManager.GetString("DZD|012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ar-EG.
        /// </summary>
        internal static string EGP_818 {
            get {
                return ResourceManager.GetString("EGP|818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tig-ER.
        /// </summary>
        internal static string ERN_232 {
            get {
                return ResourceManager.GetString("ERN|232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|wal-ET.
        /// </summary>
        internal static string ETB_230 {
            get {
                return ResourceManager.GetString("ETB|230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sv-AX|ca-AD|en-AT|nl-BE|tr-CY|et-EE|sv-FI|oc-FR|nds-DE|el-GR|fr-GP|ga-IE|it-IT|lv-LV|lt-LT|pt-LU|mt-MT|fr-GF|fr-MQ|fr-YT|fr-MC|sr-Latn-ME|nl-NL|pt-PT|fr-BL|fr-MF|fr-PM|it-SM|sk-SK|sl-SI|es-ES|it-VA.
        /// </summary>
        internal static string EUR_978 {
            get {
                return ResourceManager.GetString("EUR|978", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-FJ.
        /// </summary>
        internal static string FJD_242 {
            get {
                return ResourceManager.GetString("FJD|242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-FK.
        /// </summary>
        internal static string FKP_238 {
            get {
                return ResourceManager.GetString("FKP|238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|kw-GB|en-SH.
        /// </summary>
        internal static string GBP_826 {
            get {
                return ResourceManager.GetString("GBP|826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|os-GE.
        /// </summary>
        internal static string GEL_981 {
            get {
                return ResourceManager.GetString("GEL|981", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ha-Latn-GH.
        /// </summary>
        internal static string GHS_936 {
            get {
                return ResourceManager.GetString("GHS|936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-GI.
        /// </summary>
        internal static string GIP_292 {
            get {
                return ResourceManager.GetString("GIP|292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ff-Latn-GM.
        /// </summary>
        internal static string GMD_270 {
            get {
                return ResourceManager.GetString("GMD|270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|pt-GW.
        /// </summary>
        internal static string GNF_324 {
            get {
                return ResourceManager.GetString("GNF|324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|quc-Latn-GT.
        /// </summary>
        internal static string GTQ_320 {
            get {
                return ResourceManager.GetString("GTQ|320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-GY.
        /// </summary>
        internal static string GYD_328 {
            get {
                return ResourceManager.GetString("GYD|328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|zh-HK.
        /// </summary>
        internal static string HKD_344 {
            get {
                return ResourceManager.GetString("HKD|344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-HN.
        /// </summary>
        internal static string HNL_340 {
            get {
                return ResourceManager.GetString("HNL|340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|hr-HR.
        /// </summary>
        internal static string HRK_191 {
            get {
                return ResourceManager.GetString("HRK|191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|fr-HT.
        /// </summary>
        internal static string HTG_332 {
            get {
                return ResourceManager.GetString("HTG|332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|hu-HU.
        /// </summary>
        internal static string HUF_348 {
            get {
                return ResourceManager.GetString("HUF|348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|jv-Latn-ID.
        /// </summary>
        internal static string IDR_360 {
            get {
                return ResourceManager.GetString("IDR|360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|he-IL.
        /// </summary>
        internal static string ILS_376 {
            get {
                return ResourceManager.GetString("ILS|376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ur-IN|dz-BT.
        /// </summary>
        internal static string INR_356 {
            get {
                return ResourceManager.GetString("INR|356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|lrc-IQ.
        /// </summary>
        internal static string IQD_368 {
            get {
                return ResourceManager.GetString("IQD|368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|mzn-IR.
        /// </summary>
        internal static string IRR_364 {
            get {
                return ResourceManager.GetString("IRR|364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|is-IS.
        /// </summary>
        internal static string ISK_352 {
            get {
                return ResourceManager.GetString("ISK|352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-JM.
        /// </summary>
        internal static string JMD_388 {
            get {
                return ResourceManager.GetString("JMD|388", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|ar-JO.
        /// </summary>
        internal static string JOD_400 {
            get {
                return ResourceManager.GetString("JOD|400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|ja-JP.
        /// </summary>
        internal static string JPY_392 {
            get {
                return ResourceManager.GetString("JPY|392", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|teo-KE.
        /// </summary>
        internal static string KES_404 {
            get {
                return ResourceManager.GetString("KES|404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ru-KG.
        /// </summary>
        internal static string KGS_417 {
            get {
                return ResourceManager.GetString("KGS|417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|km-KH.
        /// </summary>
        internal static string KHR_116 {
            get {
                return ResourceManager.GetString("KHR|116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|fr-KM.
        /// </summary>
        internal static string KMF_174 {
            get {
                return ResourceManager.GetString("KMF|174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ko-KP.
        /// </summary>
        internal static string KPW_408 {
            get {
                return ResourceManager.GetString("KPW|408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string KRW_410 {
            get {
                return ResourceManager.GetString("KRW|410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|ar-KW.
        /// </summary>
        internal static string KWD_414 {
            get {
                return ResourceManager.GetString("KWD|414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-KY.
        /// </summary>
        internal static string KYD_136 {
            get {
                return ResourceManager.GetString("KYD|136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ru-KZ.
        /// </summary>
        internal static string KZT_398 {
            get {
                return ResourceManager.GetString("KZT|398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string LAK_418 {
            get {
                return ResourceManager.GetString("LAK|418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ar-LB.
        /// </summary>
        internal static string LBP_422 {
            get {
                return ResourceManager.GetString("LBP|422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ta-LK.
        /// </summary>
        internal static string LKR_144 {
            get {
                return ResourceManager.GetString("LKR|144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|vai-Vaii-LR.
        /// </summary>
        internal static string LRD_430 {
            get {
                return ResourceManager.GetString("LRD|430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|st-LS.
        /// </summary>
        internal static string LSL_426 {
            get {
                return ResourceManager.GetString("LSL|426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|ar-LY.
        /// </summary>
        internal static string LYD_434 {
            get {
                return ResourceManager.GetString("LYD|434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|zgh-Tfng-MA.
        /// </summary>
        internal static string MAD_504 {
            get {
                return ResourceManager.GetString("MAD|504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ru-MD.
        /// </summary>
        internal static string MDL_498 {
            get {
                return ResourceManager.GetString("MDL|498", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|mg-MG.
        /// </summary>
        internal static string MGA_969 {
            get {
                return ResourceManager.GetString("MGA|969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sq-MK.
        /// </summary>
        internal static string MKD_807 {
            get {
                return ResourceManager.GetString("MKD|807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|my-MM.
        /// </summary>
        internal static string MMK_104 {
            get {
                return ResourceManager.GetString("MMK|104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|mn-Mong-MN.
        /// </summary>
        internal static string MNT_496 {
            get {
                return ResourceManager.GetString("MNT|496", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MOP_446 {
            get {
                return ResourceManager.GetString("MOP|446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|fr-MR.
        /// </summary>
        internal static string MRU_929 {
            get {
                return ResourceManager.GetString("MRU|929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|mfe-MU.
        /// </summary>
        internal static string MUR_480 {
            get {
                return ResourceManager.GetString("MUR|480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|dv-MV.
        /// </summary>
        internal static string MVR_462 {
            get {
                return ResourceManager.GetString("MVR|462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-MW.
        /// </summary>
        internal static string MWK_454 {
            get {
                return ResourceManager.GetString("MWK|454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-MX.
        /// </summary>
        internal static string MXN_484 {
            get {
                return ResourceManager.GetString("MXN|484", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-MX.
        /// </summary>
        internal static string MXV_979 {
            get {
                return ResourceManager.GetString("MXV|979", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ta-MY.
        /// </summary>
        internal static string MYR_458 {
            get {
                return ResourceManager.GetString("MYR|458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|seh-MZ.
        /// </summary>
        internal static string MZN_943 {
            get {
                return ResourceManager.GetString("MZN|943", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|naq-NA.
        /// </summary>
        internal static string NAD_516 {
            get {
                return ResourceManager.GetString("NAD|516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|yo-NG.
        /// </summary>
        internal static string NGN_566 {
            get {
                return ResourceManager.GetString("NGN|566", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-NI.
        /// </summary>
        internal static string NIO_558 {
            get {
                return ResourceManager.GetString("NIO|558", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|smj-NO.
        /// </summary>
        internal static string NOK_578 {
            get {
                return ResourceManager.GetString("NOK|578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ne-NP.
        /// </summary>
        internal static string NPR_524 {
            get {
                return ResourceManager.GetString("NPR|524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|mi-NZ|en-CK|en-NU|en-PN|en-TK.
        /// </summary>
        internal static string NZD_554 {
            get {
                return ResourceManager.GetString("NZD|554", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|ar-OM.
        /// </summary>
        internal static string OMR_512 {
            get {
                return ResourceManager.GetString("OMR|512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-PA.
        /// </summary>
        internal static string PAB_590 {
            get {
                return ResourceManager.GetString("PAB|590", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|quz-PE.
        /// </summary>
        internal static string PEN_604 {
            get {
                return ResourceManager.GetString("PEN|604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-PG.
        /// </summary>
        internal static string PGK_598 {
            get {
                return ResourceManager.GetString("PGK|598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|fil-PH.
        /// </summary>
        internal static string PHP_608 {
            get {
                return ResourceManager.GetString("PHP|608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ur-PK.
        /// </summary>
        internal static string PKR_586 {
            get {
                return ResourceManager.GetString("PKR|586", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|pl-PL.
        /// </summary>
        internal static string PLN_985 {
            get {
                return ResourceManager.GetString("PLN|985", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|gn-PY.
        /// </summary>
        internal static string PYG_600 {
            get {
                return ResourceManager.GetString("PYG|600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ar-QA.
        /// </summary>
        internal static string QAR_634 {
            get {
                return ResourceManager.GetString("QAR|634", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ro-RO.
        /// </summary>
        internal static string RON_946 {
            get {
                return ResourceManager.GetString("RON|946", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sr-Latn-XK.
        /// </summary>
        internal static string RSD_941 {
            get {
                return ResourceManager.GetString("RSD|941", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tt-RU.
        /// </summary>
        internal static string RUB_643 {
            get {
                return ResourceManager.GetString("RUB|643", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|rw-RW.
        /// </summary>
        internal static string RWF_646 {
            get {
                return ResourceManager.GetString("RWF|646", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ar-SA.
        /// </summary>
        internal static string SAR_682 {
            get {
                return ResourceManager.GetString("SAR|682", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-SB.
        /// </summary>
        internal static string SBD_090 {
            get {
                return ResourceManager.GetString("SBD|090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|fr-SC.
        /// </summary>
        internal static string SCR_690 {
            get {
                return ResourceManager.GetString("SCR|690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|nus-SS.
        /// </summary>
        internal static string SDG_938 {
            get {
                return ResourceManager.GetString("SDG|938", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sv-SE.
        /// </summary>
        internal static string SEK_752 {
            get {
                return ResourceManager.GetString("SEK|752", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|zh-SG.
        /// </summary>
        internal static string SGD_702 {
            get {
                return ResourceManager.GetString("SGD|702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SHP_654 {
            get {
                return ResourceManager.GetString("SHP|654", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ff-Latn-SL.
        /// </summary>
        internal static string SLL_694 {
            get {
                return ResourceManager.GetString("SLL|694", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|so-SO.
        /// </summary>
        internal static string SOS_706 {
            get {
                return ResourceManager.GetString("SOS|706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|nl-SR.
        /// </summary>
        internal static string SRD_968 {
            get {
                return ResourceManager.GetString("SRD|968", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|nus-SS.
        /// </summary>
        internal static string SSP_728 {
            get {
                return ResourceManager.GetString("SSP|728", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|pt-ST.
        /// </summary>
        internal static string STN_930 {
            get {
                return ResourceManager.GetString("STN|930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-SV.
        /// </summary>
        internal static string SVC_222 {
            get {
                return ResourceManager.GetString("SVC|222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|syr-SY.
        /// </summary>
        internal static string SYP_760 {
            get {
                return ResourceManager.GetString("SYP|760", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SZL_748 {
            get {
                return ResourceManager.GetString("SZL|748", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|th-TH.
        /// </summary>
        internal static string THB_764 {
            get {
                return ResourceManager.GetString("THB|764", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tg-Cyrl-TJ.
        /// </summary>
        internal static string TJS_972 {
            get {
                return ResourceManager.GetString("TJS|972", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tk-TM.
        /// </summary>
        internal static string TMT_934 {
            get {
                return ResourceManager.GetString("TMT|934", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3|fr-TN.
        /// </summary>
        internal static string TND_788 {
            get {
                return ResourceManager.GetString("TND|788", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|to-TO.
        /// </summary>
        internal static string TOP_776 {
            get {
                return ResourceManager.GetString("TOP|776", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|tr-TR.
        /// </summary>
        internal static string TRY_949 {
            get {
                return ResourceManager.GetString("TRY|949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-TT.
        /// </summary>
        internal static string TTD_780 {
            get {
                return ResourceManager.GetString("TTD|780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|zh-TW.
        /// </summary>
        internal static string TWD_901 {
            get {
                return ResourceManager.GetString("TWD|901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|vun-TZ.
        /// </summary>
        internal static string TZS_834 {
            get {
                return ResourceManager.GetString("TZS|834", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|uk-UA.
        /// </summary>
        internal static string UAH_980 {
            get {
                return ResourceManager.GetString("UAH|980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|xog-UG.
        /// </summary>
        internal static string UGX_800 {
            get {
                return ResourceManager.GetString("UGX|800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|lkt-US|en-AS|en-IO|en-VG|nl-BQ|quz-EC|es-SV|en-GU|fr-HT|en-MH|en-MP|en-PW|es-PA|es-PR|pt-TL|en-TC.
        /// </summary>
        internal static string USD_840 {
            get {
                return ResourceManager.GetString("USD|840", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|lkt-US.
        /// </summary>
        internal static string USN_997 {
            get {
                return ResourceManager.GetString("USN|997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|es-UY.
        /// </summary>
        internal static string UYI_940 {
            get {
                return ResourceManager.GetString("UYI|940", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-UY.
        /// </summary>
        internal static string UYU_858 {
            get {
                return ResourceManager.GetString("UYU|858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4|es-UY.
        /// </summary>
        internal static string UYW_927 {
            get {
                return ResourceManager.GetString("UYW|927", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|uz-Latn-UZ.
        /// </summary>
        internal static string UZS_860 {
            get {
                return ResourceManager.GetString("UZS|860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|es-VE.
        /// </summary>
        internal static string VES_928 {
            get {
                return ResourceManager.GetString("VES|928", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|vi-VN.
        /// </summary>
        internal static string VND_704 {
            get {
                return ResourceManager.GetString("VND|704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|fr-VU.
        /// </summary>
        internal static string VUV_548 {
            get {
                return ResourceManager.GetString("VUV|548", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-WS.
        /// </summary>
        internal static string WST_882 {
            get {
                return ResourceManager.GetString("WST|882", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|yav-CM|sg-CF|fr-TD|pt-GQ|fr-GA.
        /// </summary>
        internal static string XAF_950 {
            get {
                return ResourceManager.GetString("XAF|950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XAG_961 {
            get {
                return ResourceManager.GetString("XAG|961", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XAU_959 {
            get {
                return ResourceManager.GetString("XAU|959", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XBA_955 {
            get {
                return ResourceManager.GetString("XBA|955", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XBB_956 {
            get {
                return ResourceManager.GetString("XBB|956", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XBC_957 {
            get {
                return ResourceManager.GetString("XBC|957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XBD_958 {
            get {
                return ResourceManager.GetString("XBD|958", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-AI|en-AG|es-DO|en-GD|en-MS|en-KN|en-LC|en-VC.
        /// </summary>
        internal static string XCD_951 {
            get {
                return ResourceManager.GetString("XCD|951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XDR_960 {
            get {
                return ResourceManager.GetString("XDR|960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|yo-BJ|fr-BF|pt-GW|ses-ML|yo-NG|wo-SN|fr-TG.
        /// </summary>
        internal static string XOF_952 {
            get {
                return ResourceManager.GetString("XOF|952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XPD_964 {
            get {
                return ResourceManager.GetString("XPD|964", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0|fr-NC|fr-WF.
        /// </summary>
        internal static string XPF_953 {
            get {
                return ResourceManager.GetString("XPF|953", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XPT_962 {
            get {
                return ResourceManager.GetString("XPT|962", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XSU_994 {
            get {
                return ResourceManager.GetString("XSU|994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XTS_963 {
            get {
                return ResourceManager.GetString("XTS|963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XUA_965 {
            get {
                return ResourceManager.GetString("XUA|965", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string XXX_999 {
            get {
                return ResourceManager.GetString("XXX|999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|ar-YE.
        /// </summary>
        internal static string YER_886 {
            get {
                return ResourceManager.GetString("YER|886", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|st-LS|naq-NA|zu-ZA.
        /// </summary>
        internal static string ZAR_710 {
            get {
                return ResourceManager.GetString("ZAR|710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|en-ZM.
        /// </summary>
        internal static string ZMW_967 {
            get {
                return ResourceManager.GetString("ZMW|967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|sn-Latn-ZW.
        /// </summary>
        internal static string ZWL_932 {
            get {
                return ResourceManager.GetString("ZWL|932", resourceCulture);
            }
        }
    }
}
