//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Types.Scalars {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScalarResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScalarResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotChocolate.Types.Scalars.ScalarResources", typeof(ScalarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NegativeIntType scalar type represents Integers that will have a value less than 0..
        /// </summary>
        internal static string NegativeIntType_Description {
            get {
                return ResourceManager.GetString("NegativeIntType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegativeIntType cannot parse the provided literal. The provided int was not negative..
        /// </summary>
        internal static string NegativeIntType_IsNotNegative_ParseLiteral {
            get {
                return ResourceManager.GetString("NegativeIntType_IsNotNegative_ParseLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegativeIntType cannot parse the provided value. The provided int was not Negative..
        /// </summary>
        internal static string NegativeIntType_IsNotNegative_ParseValue {
            get {
                return ResourceManager.GetString("NegativeIntType_IsNotNegative_ParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NonEmptyString scalar type represents non empty textual data, represented as UTF‐8 character sequences with at least one character.
        /// </summary>
        internal static string NonEmptyStringType_Description {
            get {
                return ResourceManager.GetString("NonEmptyStringType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonEmptyString cannot parse the provided literal. The provided string was empty..
        /// </summary>
        internal static string NonEmptyStringType_IsEmpty_ParseLiteral {
            get {
                return ResourceManager.GetString("NonEmptyStringType_IsEmpty_ParseLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonEmptyString cannot parse the provided value. The provided string was empty..
        /// </summary>
        internal static string NonEmptyStringType_IsEmpty_ParseValue {
            get {
                return ResourceManager.GetString("NonEmptyStringType_IsEmpty_ParseValue", resourceCulture);
            }
        }
    }
}
