{
  a: foos(where: { foo: "bar" }) {
    bar
  }
  b: foos(where: { OR: [{ foo: "bar" }, { foo_starts_with: "a" }] }) {
    bar
  }
  c: foos(
    where: {
      OR: [
        { foo: "bar" }
        { AND: [{ foo_starts_with: "a" }, { foo_starts_with: "a" }] }
      ]
    }
  ) {
    bar
  }
}
