<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CookieCrumble.Resources.AzureStorage</AssemblyName>
    <RootNamespace>CookieCrumble.Resources</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Testcontainers.Azurite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CookieCrumble.Resources/CookieCrumble.Resources.csproj" />
  </ItemGroup>

</Project>
