mutation BeginFusionDeployment($input: BeginFusionConfigurationPublishInput!) {
  beginFusionConfigurationPublish(input: $input) {
    requestId
    errors {
      __typename
      ...FusionError
    }
  }
}

mutation ClaimFusionDeployment($input: StartFusionConfigurationCompositionInput!) {
  startFusionConfigurationComposition(input: $input) {
    errors {
      __typename
      ...FusionError
    }
  }
}

mutation ReleaseFusionDeployment($input: CancelFusionConfigurationCompositionInput!) {
  cancelFusionConfigurationComposition(input: $input) {
    errors {
      __typename
      ...FusionError
    }
  }
}

mutation ValidateFusionDeployment($input: ValidateFusionConfigurationCompositionInput!) {
  validateFusionConfigurationComposition(input: $input) {
    errors {
      __typename
      ...FusionError
    }
  }
}

mutation CommitFusionDeployment($input: CommitFusionConfigurationPublishInput!) {
  commitFusionConfigurationPublish(input: $input) {
    errors {
      __typename
      ...FusionError
    }
  }
}

subscription WatchFusionDeployment($requestId: ID!) {
  onFusionConfigurationPublishingTaskChanged(requestId: $requestId) {
    __typename
    state
    ... on ProcessingTaskIsQueued {
      queuePosition
    }
    ... on FusionConfigurationPublishingFailed {
      errors {
        message
      }
    }
    ... on FusionConfigurationValidationFailed {
      errors {
        message
      }
    }
  }
}
