namespace ChilliCream.Nitro.CommandLine.Services.Hook;

/// <summary>
/// Builds the Opencode plugin shim installed by the hooks command.
/// </summary>
internal static class OpencodeHooksTemplate
{
    public const string OwnershipMarker = "nitro-opencode-hooks: managed";

    public static string Build(LaunchDescriptor descriptor)
    {
        var command = new List<string>(1 + descriptor.ArgumentPrefix.Count) { descriptor.Executable };
        command.AddRange(descriptor.ArgumentPrefix);

        return $$"""
            // {{OwnershipMarker}}
            // Generated by Nitro. Changes are replaced by `nitro agent hooks opencode install`.
            const command = {{BuildCommandArray(command)}};
            const timeoutMilliseconds = 10_000;
            const nitroPushedMetadataKey = "{{OpencodeHookProtocol.PushedPromptMetadataKey}}";
            const nitroPushedMetadataValue = "{{OpencodeHookProtocol.PushedPromptMetadataValue}}";
            const activeSessions = new Map();

            function sessionId(properties) {
              return properties.sessionID ?? properties.sessionId ?? properties.session?.id ?? properties.info?.id;
            }

            function payload(properties, serverUrl) {
              const result = {
                serverUrl: serverUrl.toString(),
                sessionId: sessionId(properties),
              };

              if (process.env.OPENCODE_SERVER_PASSWORD) {
                result.serverPassword = process.env.OPENCODE_SERVER_PASSWORD;
              }

              return result;
            }

            async function invoke(name, body) {
              try {
                const child = Bun.spawn([...command, "agent", "hook", "opencode", name], {
                  stdin: "pipe",
                  stdout: "pipe",
                  stderr: "ignore",
                });
                child.stdin.write(JSON.stringify(body));
                child.stdin.end();

                const text = await Promise.race([
                  new Response(child.stdout).text(),
                  new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), timeoutMilliseconds)),
                ]);
                const exitCode = await child.exited;

                return exitCode === 0 && text ? JSON.parse(text) : {};
              } catch {
                return {};
              }
            }

            function appendParts(output, response) {
              const parts = response.parts ?? response.additionalContext ?? [];

              for (const part of parts) {
                if (typeof part === "string") {
                  output.parts.push({ type: "text", text: part });
                } else if (part?.type === "text") {
                  output.parts.push(part);
                }
              }
            }

            function isNitroPushed(parts) {
              return (parts ?? []).some(part =>
                part?.type === "text" &&
                part?.metadata?.[nitroPushedMetadataKey] === nitroPushedMetadataValue);
            }

            export default async function nitroHooks(input) {
              const serverUrl = input.serverUrl;

              process.on("exit", () => {
                for (const [id, version] of activeSessions) {
                  void invoke("session-deleted", {
                    ...payload({ sessionID: id }, serverUrl),
                    harnessVersion: version,
                  });
                }
              });

              return {
                event: async ({ event }) => {
                  const properties = event.properties ?? {};
                  const body = payload(properties, serverUrl);

                  if (event.type === "session.created") {
                    body.harnessVersion = properties.info?.version ?? properties.session?.version;
                    if (body.sessionId) {
                      activeSessions.set(body.sessionId, body.harnessVersion);
                    }
                    await invoke("session-created", body);
                  } else if (event.type === "session.deleted") {
                    activeSessions.delete(body.sessionId);
                    await invoke("session-deleted", body);
                  } else if (
                    event.type === "session.idle" ||
                    (event.type === "session.status" && properties.status?.type === "idle")) {
                    await invoke("session-idle", body);
                  }
                },
                "chat.message": async (input, output) => {
                  const nitroPushed = isNitroPushed(input.parts);
                  const response = await invoke("chat-message", {
                    ...payload({ sessionID: input.sessionID ?? input.sessionId }, serverUrl),
                    nitroPushed,
                  });
                  appendParts(output, response);
                },
                dispose: async () => {
                  // Session deletion is the authoritative cleanup path. This is best effort only.
                },
              };
            }
            """;
    }

    private static string BuildCommandArray(IReadOnlyList<string> command)
        => $"[{string.Join(',', command.Select(static part => $"\"{EscapeJavaScriptString(part)}\""))}]";

    private static string EscapeJavaScriptString(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
}
