namespace ChilliCream.Nitro.CommandLine.Services.Hook;

/// <summary>
/// Builds the Opencode plugin shim installed by the hooks command.
/// </summary>
internal static class OpencodeHooksTemplate
{
    public const string OwnershipMarker = "nitro-opencode-hooks: managed";

    public static string Build(LaunchDescriptor descriptor)
    {
        var command = new List<string>(1 + descriptor.ArgumentPrefix.Count) { descriptor.Executable };
        command.AddRange(descriptor.ArgumentPrefix);

        return $$"""
            // {{OwnershipMarker}}
            // Generated by Nitro. Changes are replaced by `nitro agent hooks opencode install`.
            const command = {{BuildCommandArray(command)}};
            const timeoutMilliseconds = 10_000;
            const nitroPushedPrefix = "{{EscapeJavaScriptString(OpencodeHookProtocol.PushedPromptPrefix)}}";
            const activeSessions = new Map();
            // sessionId -> whether the last chat-message response's parts landed on
            // output.parts. Reported to the hook process on the next chat-message
            // payload as nitroDelivered; an absent entry means no turn has happened yet.
            const appendOutcomes = new Map();

            function sessionId(properties) {
              return properties.sessionID ?? properties.sessionId ?? properties.session?.id ?? properties.info?.id;
            }

            // Reading pluginInput.serverUrl twice and comparing by reference
            // distinguishes a bound server (same object) from an unbound one (a fresh
            // placeholder on every read).
            function payload(properties, pluginInput) {
              const first = pluginInput.serverUrl;
              const second = pluginInput.serverUrl;
              const result = {
                serverUrl: first.toString(),
                sessionId: sessionId(properties),
                serverBound: first === second,
              };

              if (process.env.OPENCODE_SERVER_PASSWORD) {
                result.serverPassword = process.env.OPENCODE_SERVER_PASSWORD;
              }

              return result;
            }

            async function invoke(name, body) {
              try {
                const child = Bun.spawn([...command, "agent", "hook", "opencode", name], {
                  stdin: "pipe",
                  stdout: "pipe",
                  stderr: "ignore",
                });
                child.stdin.write(JSON.stringify(body));
                child.stdin.end();

                const text = await Promise.race([
                  new Response(child.stdout).text(),
                  new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), timeoutMilliseconds)),
                ]);
                const exitCode = await child.exited;

                return exitCode === 0 && text ? JSON.parse(text) : undefined;
              } catch {
                return undefined;
              }
            }

            function nextSyntheticPartId(existingParts) {
              let maxId = null;

              for (const part of existingParts ?? []) {
                if (typeof part?.id === "string" && part.id.startsWith("prt_")) {
                  if (maxId === null || part.id > maxId) {
                    maxId = part.id;
                  }
                }
              }

              return maxId ?? `prt_${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;
            }

            function syntheticTextOf(part) {
              if (typeof part === "string") {
                return part;
              }

              if (part?.type === "text" && typeof part.text === "string") {
                return part.text;
              }

              return undefined;
            }

            // Appends response parts onto output.parts as synthetic text parts.
            // Returns the number of parts pushed, 0 when there was nothing to push, or
            // false when there were candidate parts but none made it onto output.parts.
            function appendParts(output, response) {
              try {
                const parts = response.parts ?? response.additionalContext ?? [];
                const sessionID = output.message?.sessionID;
                const messageID = output.message?.id;

                if (!sessionID || !messageID) {
                  return parts.length > 0 ? false : 0;
                }

                let previousId = nextSyntheticPartId(output.parts);
                let pushed = 0;

                for (const part of parts) {
                  const text = syntheticTextOf(part);

                  if (text === undefined) {
                    continue;
                  }

                  previousId = `${previousId}z`;
                  output.parts.push({
                    id: previousId,
                    sessionID,
                    messageID,
                    type: "text",
                    text,
                    synthetic: true,
                  });
                  pushed += 1;
                }

                return parts.length > 0 && pushed === 0 ? false : pushed;
              } catch {
                // Missing or malformed context is an acceptable degradation; a
                // rejected prompt is not.
                return false;
              }
            }

            function stripNitroPushedPrefix(parts) {
              let pushed = false;

              for (const part of parts ?? []) {
                if (part?.type === "text" && typeof part.text === "string" && part.text.startsWith(nitroPushedPrefix)) {
                  part.text = part.text.slice(nitroPushedPrefix.length);
                  pushed = true;
                }
              }

              return pushed;
            }

            export default async function nitroHooks(pluginInput) {
              process.on("exit", () => {
                for (const [id, version] of activeSessions) {
                  void invoke("session-deleted", {
                    ...payload({ sessionID: id }, pluginInput),
                    harnessVersion: version,
                  });
                }
              });

              return {
                event: async ({ event }) => {
                  const properties = event.properties ?? {};
                  const body = payload(properties, pluginInput);

                  if (event.type === "session.created") {
                    body.harnessVersion = properties.info?.version ?? properties.session?.version;
                    if (body.sessionId) {
                      activeSessions.set(body.sessionId, body.harnessVersion);
                    }
                    await invoke("session-created", body);
                  } else if (event.type === "session.deleted") {
                    activeSessions.delete(body.sessionId);
                    appendOutcomes.delete(body.sessionId);
                    await invoke("session-deleted", body);
                  } else if (
                    event.type === "session.idle" ||
                    (event.type === "session.status" && properties.status?.type === "idle")) {
                    await invoke("session-idle", body);
                  }
                },
                "chat.message": async (input, output) => {
                  // OpenCode exposes the message actually delivered to the
                  // model on output.parts, not input.parts, so the pushed
                  // prefix must be read and stripped there.
                  const nitroPushed = stripNitroPushedPrefix(output.parts);
                  const chatSessionId = input.sessionID ?? input.sessionId;
                  const body = {
                    ...payload({ sessionID: chatSessionId }, pluginInput),
                    nitroPushed,
                  };
                  // An absent map entry (first turn, or the server restarted) reports
                  // as false rather than being guessed as harmless.
                  const previousDelivered = appendOutcomes.get(chatSessionId) ?? false;
                  body.nitroDelivered = previousDelivered;

                  const response = await invoke("chat-message", body);
                  // response is undefined when the round trip to the hook process was
                  // lost entirely; treat it as undelivered rather than a neutral response.
                  const pushed = response === undefined ? false : appendParts(output, response);

                  if (pushed === false) {
                    appendOutcomes.set(chatSessionId, false);
                  } else if (pushed > 0) {
                    appendOutcomes.set(chatSessionId, true);
                  } else {
                    // Nothing to deliver is not a delivery failure: record true so an
                    // absent entry never means "had nothing to say".
                    appendOutcomes.set(chatSessionId, true);
                  }
                },
                dispose: async () => {
                  // Session deletion is the authoritative cleanup path. This is best effort only.
                },
              };
            }
            """;
    }

    private static string BuildCommandArray(IReadOnlyList<string> command)
        => $"[{string.Join(',', command.Select(static part => $"\"{EscapeJavaScriptString(part)}\""))}]";

    private static string EscapeJavaScriptString(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
}
