mutation PollNitroSchemaValidation($input: PollSchemaVersionValidationRequestInput!) {
  pollSchemaVersionValidationRequest(input: $input) {
    errors {
      __typename
      ... on Error {
        message
      }
    }
    result {
      __typename
      state
      ... on SchemaVersionValidationFailed {
        errors {
          __typename
          message
          ... on PersistedQueryValidationError {
            clientId
            hasMoreErrors
            client {
              id
              name
            }
            queries {
              deployedTags
              hash
              message
              errors {
                message
                code
                path
                locations {
                  line
                  column
                }
              }
            }
          }
          ... on SchemaVersionChangeViolationError {
            changes {
              ...SchemaChangeSummary
              ... on ObjectModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on InputObjectModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on DirectiveModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on ScalarModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on EnumModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on UnionModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
              ... on InterfaceModifiedChange {
                changes {
                  ...SchemaChangeDetail
                }
              }
            }
          }
          ... on InvalidGraphQLSchemaError {
            errors {
              message
              code
            }
          }
          ... on SchemaVersionSyntaxError {
            line
            column
            position
          }
          ... on OperationsAreNotAllowedError {
            operationName
          }
          ... on OpenApiCollectionValidationError {
            collections {
              openApiCollection {
                id
                name
              }
              entities {
                __typename
                ... on OpenApiCollectionValidationEndpoint {
                  httpMethod
                  route
                }
                ... on OpenApiCollectionValidationModel {
                  name
                }
                errors {
                  __typename
                  message
                  ... on OpenApiCollectionValidationDocumentError {
                    code
                    path
                    locations {
                      line
                      column
                    }
                  }
                }
              }
            }
          }
          ... on McpFeatureCollectionValidationError {
            collections {
              mcpFeatureCollection {
                id
                name
              }
              entities {
                __typename
                ... on McpFeatureCollectionValidationPrompt {
                  name
                }
                ... on McpFeatureCollectionValidationTool {
                  name
                }
                errors {
                  __typename
                  message
                  ... on McpFeatureCollectionValidationDocumentError {
                    code
                    path
                    locations {
                      line
                      column
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment SchemaChangeSummary on SchemaChangeLogEntry {
  __typename
  ... on SchemaChange {
    severity
  }
  ... on TypeSystemMemberAddedChange {
    coordinate
  }
  ... on TypeSystemMemberModifiedChange {
    coordinate
  }
  ... on TypeSystemMemberRemovedChange {
    coordinate
  }
  ... on ObjectModifiedChange {
    coordinate
  }
  ... on InputObjectModifiedChange {
    coordinate
  }
  ... on DirectiveModifiedChange {
    coordinate
  }
  ... on ScalarModifiedChange {
    coordinate
  }
  ... on EnumModifiedChange {
    coordinate
  }
  ... on UnionModifiedChange {
    coordinate
  }
  ... on InterfaceModifiedChange {
    coordinate
  }
}

fragment SchemaChangeDetail on SchemaChangeLogEntry {
  ...SchemaChangeLeaf
  ... on InputFieldChanged {
    changes {
      ...SchemaChangeLeaf
    }
  }
  ... on OutputFieldChanged {
    changes {
      ...SchemaChangeLeaf
      ... on ArgumentChanged {
        changes {
          ...SchemaChangeLeaf
        }
      }
    }
  }
  ... on ArgumentChanged {
    changes {
      ...SchemaChangeLeaf
    }
  }
  ... on EnumValueChanged {
    changes {
      ...SchemaChangeLeaf
    }
  }
}

fragment SchemaChangeLeaf on SchemaChangeLogEntry {
  ...SchemaChangeSummary
  ... on InterfaceImplementationAdded {
    interfaceName
  }
  ... on InterfaceImplementationRemoved {
    interfaceName
  }
  ... on DescriptionChanged {
    old
    new
  }
  ... on FieldAddedChange {
    coordinate
    typeName
    fieldName
  }
  ... on FieldRemovedChange {
    coordinate
    typeName
    fieldName
  }
  ... on InputFieldChanged {
    coordinate
    fieldName
  }
  ... on OutputFieldChanged {
    coordinate
    fieldName
  }
  ... on PossibleTypeAdded {
    typeName
  }
  ... on PossibleTypeRemoved {
    typeName
  }
  ... on UnionMemberAdded {
    typeName
  }
  ... on UnionMemberRemoved {
    typeName
  }
  ... on DirectiveLocationAdded {
    location
  }
  ... on DirectiveLocationRemoved {
    location
  }
  ... on DeprecatedChange {
    deprecationReason
  }
  ... on ArgumentAdded {
    coordinate
    name
    typeName
  }
  ... on ArgumentRemoved {
    coordinate
    name
    typeName
  }
  ... on ArgumentChanged {
    coordinate
    name
  }
  ... on EnumValueAdded {
    coordinate
  }
  ... on EnumValueRemoved {
    coordinate
  }
  ... on EnumValueChanged {
    coordinate
  }
  ... on TypeChanged {
    oldType
    newType
  }
}
