<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <LangVersion>Preview</LangVersion>
    <AssemblyName>HotChocolate.Language.Benchmarks</AssemblyName>
    <RootNamespace>HotChocolate.Language.Benchmarks</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Language.Utf8\HotChocolate.Language.Utf8.csproj" />
  </ItemGroup>

</Project>
