<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageVersion Include="Aspire.Hosting.Azure.AppContainers" Version="13.4.6" />
    <PackageVersion Include="ChilliCream.Nitro" Version="16.5.0" />
    <PackageVersion Include="ChilliCream.Nitro.Fusion" Version="16.5.0" />
    <PackageVersion Include="HotChocolate.Fusion.AspNetCore" Version="16.5.0" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>
</Project>
