//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Execution.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotChocolate.Execution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errorMessage mustn&apos;t be null or empty..
        /// </summary>
        internal static string MiddlewareContext_ReportErrorCannotBeNull {
            get {
                return ResourceManager.GetString("MiddlewareContext_ReportErrorCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is full..
        /// </summary>
        internal static string ObjectBuffer_IsEmpty {
            get {
                return ResourceManager.GetString("ObjectBuffer_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is used up..
        /// </summary>
        internal static string ObjectBuffer_IsUsedUp {
            get {
                return ResourceManager.GetString("ObjectBuffer_IsUsedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection is read-only..
        /// </summary>
        internal static string PreparedSelection_ReadOnly {
            get {
                return ResourceManager.GetString("PreparedSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field `{0}` does not exist on type `{1}`..
        /// </summary>
        internal static string ThrowHelper_FieldDoesNotExistOnType {
            get {
                return ResourceManager.GetString("ThrowHelper_FieldDoesNotExistOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}-directive is missing the if-argument..
        /// </summary>
        internal static string ThrowHelper_MissingDirectiveIfArgument {
            get {
                return ResourceManager.GetString("ThrowHelper_MissingDirectiveIfArgument", resourceCulture);
            }
        }
        
        internal static string DeferredResult_ReadResultsAsync_ReadOnlyOnce {
            get {
                return ResourceManager.GetString("DeferredResult_ReadResultsAsync_ReadOnlyOnce", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_ArgumentNonNullError_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_ArgumentNonNullError_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_UnableToResolveTheAbstractType_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_UnableToResolveTheAbstractType_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_ListValueIsNotSupported_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_ListValueIsNotSupported_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_UnexpectedValueCompletionError_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_UnexpectedValueCompletionError_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_RootTypeNotFound_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_RootTypeNotFound_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_StateInvalidForOperationResolver_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_StateInvalidForOperationResolver_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_StateInvalidForOperationVariableCoercion_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_StateInvalidForOperationVariableCoercion_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_StateInvalidForOperationExecution_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_StateInvalidForOperationExecution_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_ValueCompletion_CouldNotResolveAbstractType_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_ValueCompletion_CouldNotResolveAbstractType_Message", resourceCulture);
            }
        }
        
        internal static string ErrorHelper_StateInvalidForDocumentValidation_Message {
            get {
                return ResourceManager.GetString("ErrorHelper_StateInvalidForDocumentValidation_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_VariableIsNotAnInputType_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_VariableIsNotAnInputType_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_NonNullVariableIsNull_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_NonNullVariableIsNull_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_VariableValueInvalidType_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_VariableValueInvalidType_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_QueryTypeNotSupported_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_QueryTypeNotSupported_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_VariableNotFound_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_VariableNotFound_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_VariableNotOfType_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_VariableNotOfType_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_RootTypeNotSupported_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_RootTypeNotSupported_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_SubscriptionExecutor_ContextInvalidState_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_SubscriptionExecutor_ContextInvalidState_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_SubscriptionExecutor_SubscriptionsMustHaveOneField_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_SubscriptionExecutor_SubscriptionsMustHaveOneField_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_SubscriptionExecutor_NoSubscribeResolver_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_SubscriptionExecutor_NoSubscribeResolver_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_ResolverContext_LiteralsNotSupported_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_ResolverContext_LiteralsNotSupported_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_ResolverContext_CannotConvertArgument_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_ResolverContext_CannotConvertArgument_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_ResolverContext_LiteralNotCompatible_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_ResolverContext_LiteralNotCompatible_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_ResolverContext_ArgumentDoesNotExist_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_ResolverContext_ArgumentDoesNotExist_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_OperationResolverHelper_NoOperationFound_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_OperationResolverHelper_NoOperationFound_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_OperationResolverHelper_MultipleOperation_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_OperationResolverHelper_MultipleOperation_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_OperationResolverHelper_InvalidOperationName_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_OperationResolverHelper_InvalidOperationName_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_BatchExecutor_CannotSerializeVariable_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_BatchExecutor_CannotSerializeVariable_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_CollectVariablesVisitor_NoCompatibleType_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_CollectVariablesVisitor_NoCompatibleType_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_FieldVisibility_ValueNotSupported_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_FieldVisibility_ValueNotSupported_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_QueryCompiler_CompositeTypeSelectionSet_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_QueryCompiler_CompositeTypeSelectionSet_Message", resourceCulture);
            }
        }
        
        internal static string ThrowHelper_OperationExecutionMiddleware_NoBatchDispatcher_Message {
            get {
                return ResourceManager.GetString("ThrowHelper_OperationExecutionMiddleware_NoBatchDispatcher_Message", resourceCulture);
            }
        }
    }
}
