enableHardenedMode: true

enableScripts: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/enforce-devcontainer.cjs

# 7 days (in minutes)
npmMinimalAgeGate: 10080

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.15.0.cjs
