nodeLinker: node-modules

# 7 days (in minutes)
npmMinimalAgeGate: 10080

enableScripts: false
enableHardenedMode: true

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.14.1.cjs
