enableHardenedMode: true

enableScripts: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/enforce-devcontainer.cjs

# 7 days (in minutes)
npmMinimalAgeGate: 10080

# FontAwesome generates and hosts the package below for us
npmPreapprovedPackages:
  - "@awesome.me/kit-04be88f754"

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.15.0.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}
