<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <TargetFramework>$(DemoTargetFramework)</TargetFramework>
    <TargetFrameworks>$(DemoTargetFramework)</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
