name: Test123

on:
  pull_request:
    branches:
      - main

jobs:
  configure:
    name: Generate Test Matrix
    runs-on: test-runner

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.x
            8.x

      - name: Generate Test Matrix
        run: dotnet --info


